#!/bin/sh
set -eu

script_dir="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
pak_dir="$(CDPATH= cd -- "$script_dir/.." && pwd)"
platform="${PLATFORM:-mlp1}"

resolver="$script_dir/resolve-sdcard-root.sh"
if [ -z "${SDCARD_PATH:-}" ]; then
  if [ -f "$resolver" ]; then
    SDCARD_PATH="$(PLATFORM="$platform" "$resolver" "$pak_dir")"
  else
    case "$pak_dir" in
      */Apps/*/*.pak) SDCARD_PATH="$(CDPATH= cd -- "$pak_dir/../../.." && pwd)" ;;
      *) echo "cannot resolve Leaf SD root; set SDCARD_PATH" >&2; exit 1 ;;
    esac
  fi
fi
export SDCARD_PATH
export PLATFORM="$platform"

userdata_path="${USERDATA_PATH:-$SDCARD_PATH/.userdata/$platform}"
data_dir="${PORTMASTER_MLP1_DATA_DIR:-$userdata_path/portmaster}"
leaf_dir="$data_dir/.leaf"
portmaster_dir="${PORTMASTER_CONTROLFOLDER:-$data_dir/PortMaster}"
ports_dir="${ROMS_PATH:-$SDCARD_PATH/Roms}/PORTS"
logs_dir="${LOGS_PATH:-$userdata_path/logs}"
tools_dir="${LEAF_PM_TOOLS_DIR:-$data_dir/compat/tools/aarch64/bin}"
manager_bin="$pak_dir/bin/portmaster-mlp1"

export USERDATA_PATH="$userdata_path"
export PORTMASTER_MLP1_PAK_DIR="$pak_dir"
export PORTMASTER_MLP1_DATA_DIR="$data_dir"
export PORTMASTER_CONTROLFOLDER="$portmaster_dir"
export LEAF_PM_TOOLS_DIR="$tools_dir"
if [ -d "$tools_dir" ]; then
  case ":${PATH:-}:" in
    *:"$tools_dir":*) ;;
    *) PATH="$tools_dir:${PATH:-/usr/bin:/usr/sbin:/bin:/sbin}" ;;
  esac
fi
export PATH

timestamp="$(date -u +%Y%m%dT%H%M%SZ 2>/dev/null || date +%s)"
support_dir="$leaf_dir/support"
out_path="${1:-$support_dir/leaf-pm-support-$timestamp.zip}"
case "$out_path" in
  /*) ;;
  *) out_path="$(pwd)/$out_path" ;;
esac

out_dir="$(dirname -- "$out_path")"
work_dir="$support_dir/work-$timestamp-$$"
tmp_zip="$out_path.tmp.$$"

cleanup() {
  rm -rf "$work_dir" 2>/dev/null || true
  rm -f "$tmp_zip" 2>/dev/null || true
}
trap cleanup EXIT HUP INT TERM

mkdir -p "$out_dir" "$work_dir"

write_text() {
  rel="$1"
  shift
  mkdir -p "$work_dir/$(dirname -- "$rel")"
  {
    for line in "$@"; do
      printf '%s\n' "$line"
    done
  } >"$work_dir/$rel"
}

capture_cmd() {
  rel="$1"
  shift
  mkdir -p "$work_dir/$(dirname -- "$rel")"
  set +e
  {
    printf '$'
    for arg in "$@"; do
      printf ' %s' "$arg"
    done
    printf '\n\n'
    "$@"
    rc=$?
    printf '\nexit_status=%s\n' "$rc"
  } >"$work_dir/$rel" 2>&1
  set -e
}

capture_shell() {
  rel="$1"
  command="$2"
  mkdir -p "$work_dir/$(dirname -- "$rel")"
  set +e
  {
    printf '$ %s\n\n' "$command"
    sh -c "$command"
    rc=$?
    printf '\nexit_status=%s\n' "$rc"
  } >"$work_dir/$rel" 2>&1
  set -e
}

copy_file() {
  src="$1"
  rel="$2"
  [ -f "$src" ] || return 0
  mkdir -p "$work_dir/$(dirname -- "$rel")"
  cp -f "$src" "$work_dir/$rel"
}

tail_file() {
  src="$1"
  rel="$2"
  lines="${3:-200}"
  [ -f "$src" ] || return 0
  mkdir -p "$work_dir/$(dirname -- "$rel")"
  {
    printf 'path=%s\n' "$src"
    printf 'tail_lines=%s\n\n' "$lines"
    tail -n "$lines" "$src"
  } >"$work_dir/$rel" 2>&1
}

safe_name() {
  printf '%s' "$1" | tr '/ ' '__' | tr -c 'A-Za-z0-9._-' '_'
}

write_text README.txt \
  "Leaf PortMaster support bundle" \
  "" \
  "Generated: $timestamp" \
  "Platform: $platform" \
  "SDCARD_PATH: $SDCARD_PATH" \
  "USERDATA_PATH: $userdata_path" \
  "PORTMASTER_MLP1_DATA_DIR: $data_dir" \
  "" \
  "This bundle is generated by the optional PortMaster.pak. It writes only to the requested output path and temporary files under $support_dir while building." \
  "" \
  "Useful starting points:" \
  "- commands/doctor-cfw.txt and commands/doctor-cfw.json" \
  "- commands/ui-state.txt" \
  "- leaf/launch-env*.json and leaf/launch-env*.txt" \
  "- leaf/smoke/latest.tsv and leaf/smoke/latest.json" \
  "- logs/portmaster-mlp1.log.tail.txt" \
  "- port-logs/*.tail.txt" \
  "" \
  "SSH debug flow:" \
  "1. Install or launch SSHServer.pak from Apps/mlp1 if available." \
  "2. Connect to the device over the advertised network address and then cd to the SD root." \
  "3. Use the app-local tools first: export PATH=\"$tools_dir:\$PATH\"." \
  "4. Re-run probes from PortMaster.pak, for example ./launch.sh --doctor-cfw-text or LEAF_PM_ENV_PROBE=1 from a port script." \
  "" \
  "The bundle intentionally avoids broad userdata recursion, save data, PulseAudio cookies, backups, staging downloads, and full PortMaster runtime trees."

write_text context/paths.txt \
  "pak_dir=$pak_dir" \
  "platform=$platform" \
  "sdcard_path=$SDCARD_PATH" \
  "userdata_path=$userdata_path" \
  "data_dir=$data_dir" \
  "leaf_dir=$leaf_dir" \
  "portmaster_dir=$portmaster_dir" \
  "ports_dir=$ports_dir" \
  "logs_dir=$logs_dir" \
  "tools_dir=$tools_dir"

capture_cmd commands/doctor-cfw.json "$manager_bin" --doctor-cfw-json
capture_cmd commands/doctor-cfw.txt "$manager_bin" --doctor-cfw-text
capture_cmd commands/ui-state.txt "$manager_bin" --ui-state-text
capture_cmd commands/lock-summary.txt "$manager_bin" --lock-summary
capture_cmd commands/controller-layout.txt "$manager_bin" --controller-layout
capture_cmd commands/check-portmaster-update-cached.txt "$manager_bin" --check-portmaster-update-cached

capture_shell system/uname.txt "uname -a; printf '\n'; cat /proc/version 2>/dev/null || true"
capture_shell system/os-release.txt "cat /etc/os-release 2>/dev/null || true"
capture_shell system/kernel-config-summary.txt "if [ -f /proc/config.gz ]; then zcat /proc/config.gz 2>/dev/null; elif [ -f /boot/config ]; then cat /boot/config; fi | grep -Ei 'SQUASHFS|LOOP|ZRAM|UINPUT|TMPFS|OVERLAY|BINFMT|COMPAT' || true"
capture_shell system/storage.txt "df -h '$SDCARD_PATH' '$userdata_path' 2>/dev/null; printf '\n/proc/mounts filtered:\n'; grep -E 'sdcard|mmc|vfat|exfat|squashfs|zram|loop' /proc/mounts 2>/dev/null || true; printf '\n/proc/swaps:\n'; cat /proc/swaps 2>/dev/null || true"
capture_shell system/devices.txt "ls -l /dev/uinput /dev/dri /dev/dri/* /dev/loop* 2>/dev/null || true"
capture_shell system/ssh.txt "printf 'SSHServer.pak: '; [ -d '$SDCARD_PATH/Apps/$platform/SSHServer.pak' ] && echo installed || echo missing; printf '\nProcesses:\n'; ps -eo pid,args 2>/dev/null | grep -E 'dropbear|sshd' | grep -v grep || true; printf '\nListening TCP:\n'; (netstat -ltn 2>/dev/null || ss -ltn 2>/dev/null || true) | grep -E ':22|:222' || true"
capture_shell system/tool-versions.txt "for c in bash zip unzip sed find grep xargs rsync strace ldd readelf file xdelta3 7z 7za innoextract dos2unix systemctl sudo doas leaf-squashfs-check squashfuse; do printf '%s: ' \"\$c\"; command -v \"\$c\" 2>/dev/null || echo missing; done"

copy_file "$leaf_dir/manifest.json" leaf/manifest.json
copy_file "$leaf_dir/gui-update-state.json" leaf/gui-update-state.json
copy_file "$leaf_dir/armhf-scan.json" leaf/armhf-scan.json
copy_file "$leaf_dir/armhf-scan.tsv" leaf/armhf-scan.tsv
copy_file "$leaf_dir/armhf-scan.manifest" leaf/armhf-scan.manifest
copy_file "$leaf_dir/smoke/latest.json" leaf/smoke/latest.json
copy_file "$leaf_dir/smoke/latest.tsv" leaf/smoke/latest.tsv
copy_file "$leaf_dir/logs/update.log" leaf/logs/update.log
copy_file "$leaf_dir/logs/download.log" leaf/logs/download.log

for f in "$leaf_dir"/launch-env*.json "$leaf_dir"/launch-env*.txt; do
  [ -f "$f" ] || continue
  copy_file "$f" "leaf/$(basename -- "$f")"
done

if [ -d "$leaf_dir/smoke/logs" ]; then
  find "$leaf_dir/smoke/logs" -maxdepth 1 -type f | sort | while IFS= read -r f; do
    copy_file "$f" "leaf/smoke/logs/$(basename -- "$f")"
  done
fi

for f in "$pak_dir"/locks/*.json; do
  [ -f "$f" ] || continue
  copy_file "$f" "locks/$(basename -- "$f")"
done

copy_file "$data_dir/runtime/.leaf-runtime-manifest.json" versions/ui-runtime-manifest.json
copy_file "$data_dir/compat/armhf/.leaf-armhf-compat-manifest.json" versions/armhf-compat-manifest.json
copy_file "$data_dir/compat/mali/aarch64/manifest.json" versions/aarch64-mali-manifest.json
copy_file "$data_dir/compat/sdl2/aarch64/manifest.json" versions/aarch64-sdl2-fullscreen-manifest.json
copy_file "$data_dir/compat/tools/aarch64/manifest.json" versions/aarch64-tools-manifest.json
copy_file "$data_dir/compat/libs/aarch64/manifest.json" versions/aarch64-compat-libs-manifest.json
copy_file "$portmaster_dir/version" versions/upstream-portmaster-version.txt

tail_file "$logs_dir/portmaster-mlp1.log" logs/portmaster-mlp1.log.tail.txt 400
tail_file "$logs_dir/portmaster-mlp1.txt" logs/portmaster-mlp1.txt.tail.txt 400
tail_file "$portmaster_dir/log.txt" logs/upstream-portmaster-log.txt.tail.txt 400
tail_file "$portmaster_dir/PortMaster.log" logs/upstream-portmaster-PortMaster.log.tail.txt 400

if [ -d "$ports_dir" ]; then
  find "$ports_dir" -maxdepth 4 -type f \( -name 'log.txt' -o -name 'patchlog.txt' -o -name 'patcherr.txt' -o -name '*.log' \) | sort | while IFS= read -r f; do
    rel="$f"
    case "$rel" in
      "$ports_dir"/*) rel="${rel#"$ports_dir"/}" ;;
    esac
    tail_file "$f" "port-logs/$(safe_name "$rel").tail.txt" 220
  done
fi

capture_shell listings/leaf-files.txt "find '$leaf_dir' -maxdepth 3 -type f 2>/dev/null | sed 's#^$leaf_dir/##' | sort | grep -Ev '(^backups/|^downloads/|^staging/|^support/)' || true"
capture_shell listings/installed-paks.txt "find '$SDCARD_PATH/Apps/$platform' -maxdepth 2 -type d -name '*.pak' 2>/dev/null | sort || true"
capture_shell listings/installed-ports.txt "find '$ports_dir' -maxdepth 2 \\( -name '*.sh' -o -name 'port.json' \\) 2>/dev/null | sort || true"

if ! command -v zip >/dev/null 2>&1; then
  echo "zip not found; expected app-local zip at $tools_dir/bin/zip" >&2
  exit 1
fi

rm -f "$tmp_zip"
(CDPATH= cd -- "$work_dir" && zip -X -qr "$tmp_zip" .)
mv -f "$tmp_zip" "$out_path"
trap - EXIT HUP INT TERM
rm -rf "$work_dir"

printf '%s\n' "$out_path"
