#!/usr/bin/env bash
set -euo pipefail

platform="${PLATFORM:-mlp1}"
sdcard_path="${SDCARD_PATH:-}"
if [ -z "$sdcard_path" ]; then
  for candidate in /mnt/sdcard /media/sdcard1; do
    if [ -f "$candidate/.system/leaf/platforms/$platform/enabled" ]; then
      sdcard_path="$candidate"
      break
    fi
  done
fi
if [ -z "$sdcard_path" ]; then
  for candidate in /mnt/sdcard /media/sdcard1; do
    if [ -d "$candidate/.userdata/$platform/portmaster" ]; then
      sdcard_path="$candidate"
      break
    fi
  done
fi
if [ -z "$sdcard_path" ]; then
  for candidate in /mnt/sdcard /media/sdcard1; do
    if [ -d "$candidate/Roms" ]; then
      sdcard_path="$candidate"
      break
    fi
  done
fi
sdcard_path="${sdcard_path:-/mnt/sdcard}"

userdata_path="${USERDATA_PATH:-$sdcard_path/.userdata/$platform}"
data_dir="${PORTMASTER_MLP1_DATA_DIR:-$userdata_path/portmaster}"
controlfolder="${PORTMASTER_CONTROLFOLDER:-$data_dir/PortMaster}"
compat_root="${LEAF_PM_ARMHF_ROOT:-$data_dir/compat/armhf}"
ports_dir="${1:-${ROMS_PATH:-$sdcard_path/Roms}/PORTS}"
leaf_dir="$data_dir/.leaf"
report_tsv="${LEAF_PM_ARMHF_SCAN_TSV:-$leaf_dir/armhf-scan.tsv}"
report_json="${LEAF_PM_ARMHF_SCAN_JSON:-$leaf_dir/armhf-scan.json}"
hook_path="$controlfolder/leaf-armhf-env.sh"
full_port_scan="${LEAF_PM_FULL_PORT_SCAN:-0}"
scan_mode="fast"
if [ "$full_port_scan" = "1" ] || [ "$full_port_scan" = "true" ] || [ "$full_port_scan" = "yes" ]; then
  scan_mode="full"
fi
controller_x360="1900fe3c039900001399000002010000,Loong Gamepad,a:b0,b:b1,x:b3,y:b2,back:b8,guide:b10,start:b9,leftstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,lefttrigger:b6,righttrigger:b7,crc:3cfe,platform:Linux"
controller_gui="1900fe3c039900001399000002010000,Loong Gamepad,a:b1,b:b0,x:b3,y:b2,back:b8,guide:b10,start:b9,leftstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,lefttrigger:b6,righttrigger:b7,crc:3cfe,platform:Linux"
controller_nintendo="1900fe3c039900001399000002010000,Loong Gamepad,a:b1,b:b0,x:b2,y:b3,back:b8,guide:b10,start:b9,leftstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,lefttrigger:b6,righttrigger:b7,crc:3cfe,platform:Linux"

log() {
  printf 'leaf armhf scan: %s\n' "$*" >&2
}

json_escape() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g; s/	/\\t/g'
}

shell_quote() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

mkdir -p "$leaf_dir"

if [ ! -d "$ports_dir" ]; then
  log "ports dir missing: $ports_dir"
  exit 1
fi

compat_available=0
if [ -f "$compat_root/lib/ld-linux-armhf.so.3" ] &&
   [ -f "$compat_root/bin/leaf-armhf-run" ]; then
  compat_available=1
  chmod 755 "$compat_root/lib/ld-linux-armhf.so.3" "$compat_root/bin/leaf-armhf-run" 2>/dev/null || true
fi

write_leaf_hook() {
  [ -d "$controlfolder" ] || return 0

  tmp="$hook_path.tmp.$$"
  cat >"$tmp" <<EOF
#!/bin/sh
# Generated by PortMaster-mlp1. Safe to overwrite.

_leaf_pm_controlfolder="\${controlfolder:-\${PORTMASTER_CONTROLFOLDER:-$controlfolder}}"
if [ -n "\$_leaf_pm_controlfolder" ] && [ -d "\$_leaf_pm_controlfolder/.." ]; then
  _leaf_pm_data_dir="\$(CDPATH= cd -- "\$_leaf_pm_controlfolder/.." && pwd)"
else
  _leaf_pm_data_dir="$data_dir"
fi
export LEAF_PM_DATA_DIR="\$_leaf_pm_data_dir"
export PORTMASTER_CONTROLFOLDER="\${PORTMASTER_CONTROLFOLDER:-\$_leaf_pm_controlfolder}"
export HOME="\$LEAF_PM_DATA_DIR"
export XDG_DATA_HOME="\$LEAF_PM_DATA_DIR"
export HM_TOOLS_DIR="\${HM_TOOLS_DIR:-\$LEAF_PM_DATA_DIR}"
if [ -n "\${ROMS_PATH:-}" ]; then
  _leaf_pm_roms_dir="\${ROMS_PATH%/}"
  _leaf_pm_ports_dir="\$ROMS_PATH/PORTS"
elif [ -n "\${SDCARD_PATH:-}" ]; then
  _leaf_pm_roms_dir="\${SDCARD_PATH%/}/Roms"
  _leaf_pm_ports_dir="\$SDCARD_PATH/Roms/PORTS"
else
  _leaf_pm_roms_dir=""
  _leaf_pm_ports_dir="/\${directory:-roms}/ports"
fi
if [ -n "\$_leaf_pm_roms_dir" ] &&
   ! awk '\$2 == "/roms/ports" { found = 1 } END { exit found ? 0 : 1 }' /proc/mounts 2>/dev/null; then
  export directory="\${_leaf_pm_roms_dir#/}"
fi
export HM_PORTS_DIR="\${HM_PORTS_DIR:-\$_leaf_pm_ports_dir}"
export HM_SCRIPTS_DIR="\${HM_SCRIPTS_DIR:-\$HM_PORTS_DIR}"

export LEAF_PM_EGL_SHIM_DIR="\${LEAF_PM_EGL_SHIM_DIR:-\$LEAF_PM_DATA_DIR/compat/egl/aarch64}"
export LEAF_PM_MALI_AARCH64_DIR="\${LEAF_PM_MALI_AARCH64_DIR:-\$LEAF_PM_DATA_DIR/compat/mali/aarch64}"
leaf_pm_enable_godot_wayland_runtime() {
  [ "\${DEVICE_ARCH:-aarch64}" = "aarch64" ] || return 0
  export LEAF_PM_SKIP_WESTONPACK_CLEANUP="\${LEAF_PM_SKIP_WESTONPACK_CLEANUP:-1}"
  _leaf_pm_env_bin="\$(command -v env 2>/dev/null || printf '%s\n' /usr/bin/env)"
  env() {
    if [ "\${1##*/}" = "westonwrap.sh" ] && [ "\${2:-}" != "cleanup" ] && [ "\$#" -ge 6 ]; then
      # MLP1 already has Leaf's Weston running; PortMaster's nested Westonpack
      # wrapper cannot provide the EGL display Godot 4 expects on stock firmware.
      shift
      shift 4
      while [ "\$#" -gt 0 ]; do
        case "\$1" in
          *=*) export "\$1"; shift ;;
          *) break ;;
        esac
      done
      [ "\$#" -gt 0 ] || return 127
      _leaf_pm_godot_cmd="\$1"
      shift
      _leaf_pm_wayland_runtime="\${LEAF_PM_WAYLAND_RUNTIME_DIR:-\${XDG_RUNTIME_DIR:-/run}}"
      _leaf_pm_wayland_display="\${LEAF_PM_WAYLAND_DISPLAY:-\${WAYLAND_DISPLAY:-wayland-0}}"
      _leaf_pm_egl_shim="\${LEAF_PM_EGL_SHIM_DIR:-}/libEGL.so.1"
      if [ -f "\${LEAF_PM_MALI_AARCH64_DIR:-}/libmali.so.1" ]; then
        export LEAF_PM_MALI_LIB="\$LEAF_PM_MALI_AARCH64_DIR/libmali.so.1"
        case ":\${LD_LIBRARY_PATH:-}:" in
          *:"\$LEAF_PM_MALI_AARCH64_DIR":*) ;;
          *) export LD_LIBRARY_PATH="\$LEAF_PM_MALI_AARCH64_DIR\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}" ;;
        esac
      fi
      if [ -f "\$_leaf_pm_egl_shim" ]; then
        case ":\${LD_LIBRARY_PATH:-}:" in
          *:"\$LEAF_PM_EGL_SHIM_DIR":*) ;;
          *) export LD_LIBRARY_PATH="\$LEAF_PM_EGL_SHIM_DIR\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}" ;;
        esac
      fi
      _leaf_pm_has_display_driver=0
      for _leaf_pm_arg in "\$@"; do
        [ "\$_leaf_pm_arg" = "--display-driver" ] && _leaf_pm_has_display_driver=1
      done
      if [ "\$_leaf_pm_has_display_driver" -eq 1 ]; then
        "\$_leaf_pm_env_bin" \
          XDG_RUNTIME_DIR="\$_leaf_pm_wayland_runtime" \
          WAYLAND_DISPLAY="\$_leaf_pm_wayland_display" \
          SDL_VIDEODRIVER=wayland \
          "\$_leaf_pm_godot_cmd" "\$@"
        return \$?
      fi
      "\$_leaf_pm_env_bin" \
        XDG_RUNTIME_DIR="\$_leaf_pm_wayland_runtime" \
        WAYLAND_DISPLAY="\$_leaf_pm_wayland_display" \
        SDL_VIDEODRIVER=wayland \
        "\$_leaf_pm_godot_cmd" --display-driver wayland "\$@"
      return \$?
    fi
    "\$_leaf_pm_env_bin" "\$@"
  }
}

leaf_pm_enable_egl_gles_shim() {
  leaf_pm_enable_godot_wayland_runtime "\$@"
}

export LEAF_PM_RUNTIME_DIR="\${LEAF_PM_RUNTIME_DIR:-\$LEAF_PM_DATA_DIR/runtime}"
if [ -x "\$LEAF_PM_RUNTIME_DIR/bin/python3" ]; then
  _leaf_pm_python_shim_dir="/tmp/leaf-portmaster-python"
  if mkdir -p "\$_leaf_pm_python_shim_dir" 2>/dev/null; then
    cat >"\$_leaf_pm_python_shim_dir/python3" <<'LEAF_PM_PYTHON_SHIM'
#!/bin/sh
_runtime="\${LEAF_PM_RUNTIME_DIR:-}"
if [ -z "\$_runtime" ] || [ ! -x "\$_runtime/bin/python3" ]; then
  echo "Leaf PortMaster python runtime missing" >&2
  exit 127
fi
if [ -n "\${LD_LIBRARY_PATH:-}" ]; then
  export LD_LIBRARY_PATH="\$_runtime/lib:\$LD_LIBRARY_PATH"
else
  export LD_LIBRARY_PATH="\$_runtime/lib"
fi
export PYTHONHOME="\$_runtime"
export PYTHONPATH="\$_runtime/lib/python3.10:\$_runtime/lib/python3.10/site-packages:\$_runtime/lib\${PYTHONPATH:+:\$PYTHONPATH}"
export PYTHONDONTWRITEBYTECODE="\${PYTHONDONTWRITEBYTECODE:-1}"
exec "\$_runtime/bin/python3" "\$@"
LEAF_PM_PYTHON_SHIM
    chmod 755 "\$_leaf_pm_python_shim_dir/python3" 2>/dev/null || true
    cp -f "\$_leaf_pm_python_shim_dir/python3" "\$_leaf_pm_python_shim_dir/python" 2>/dev/null || true
    case ":\${PATH:-}:" in
      *:"\$_leaf_pm_python_shim_dir":*) ;;
      *) export PATH="\$_leaf_pm_python_shim_dir:\${PATH:-/usr/bin:/usr/sbin}" ;;
    esac
  fi
fi

leaf_pm_apply_controller_layout() {
  if [ "\${PORTMASTER_LEAF_PORT_LAYOUT_SCOPE:-ports}" = "gui" ]; then
    export PORTMASTER_LEAF_CONTROLLER_LAYOUT="gui"
    export SDL_GAMECONTROLLERCONFIG='$controller_gui'
  elif [ -f "\$LEAF_PM_DATA_DIR/nintendo" ]; then
    export PORTMASTER_LEAF_CONTROLLER_LAYOUT="nintendo"
    export SDL_GAMECONTROLLERCONFIG='$controller_nintendo'
  else
    export PORTMASTER_LEAF_CONTROLLER_LAYOUT="x360"
    export SDL_GAMECONTROLLERCONFIG='$controller_x360'
  fi
  export sdl_controllerconfig="\$SDL_GAMECONTROLLERCONFIG"
  export SDL_GAMECONTROLLERCONFIG_FILE="/tmp/leaf-portmaster-gamecontrollerdb.txt"
  printf '%s\n' "\$SDL_GAMECONTROLLERCONFIG" >"\$SDL_GAMECONTROLLERCONFIG_FILE" 2>/dev/null || true
}

if declare -f get_controls >/dev/null 2>&1; then
  if ! declare -f leaf_pm_upstream_get_controls >/dev/null 2>&1; then
    eval "\$(declare -f get_controls | sed '1s/get_controls/leaf_pm_upstream_get_controls/')"
  fi
  get_controls() {
    leaf_pm_upstream_get_controls "\$@"
    leaf_pm_apply_controller_layout
  }
fi

leaf_pm_apply_controller_layout

export DEVICE_HAS_ARMHF="\${DEVICE_HAS_ARMHF:-N}"
export DEVICE_HAS_AARCH64="\${DEVICE_HAS_AARCH64:-Y}"

export LEAF_PM_ARMHF_ROOT="\${LEAF_PM_ARMHF_ROOT:-\$LEAF_PM_DATA_DIR/compat/armhf}"
if [ -f "\$LEAF_PM_ARMHF_ROOT/lib/ld-linux-armhf.so.3" ] && [ -f "\$LEAF_PM_ARMHF_ROOT/bin/leaf-armhf-run" ]; then
  export DEVICE_HAS_ARMHF="Y"
  export LEAF_PM_ARMHF_LOADER="\$LEAF_PM_ARMHF_ROOT/lib/ld-linux-armhf.so.3"
  export LEAF_PM_ARMHF_RUN="\$LEAF_PM_ARMHF_ROOT/bin/leaf-armhf-run"
  export LEAF_PM_ARMHF_LIB_PATH="\$LEAF_PM_ARMHF_ROOT/usr/lib/arm-linux-gnueabihf/mali:\$LEAF_PM_ARMHF_ROOT/lib/arm-linux-gnueabihf:\$LEAF_PM_ARMHF_ROOT/usr/lib/arm-linux-gnueabihf:\$LEAF_PM_ARMHF_ROOT/usr/lib/arm-linux-gnueabihf/pulseaudio:\$LEAF_PM_ARMHF_ROOT/lib:\$LEAF_PM_ARMHF_ROOT/usr/lib"

  leaf_pm_armhf_run() {
    "\$LEAF_PM_ARMHF_RUN" "\$@"
  }
fi

unset _leaf_pm_controlfolder _leaf_pm_data_dir _leaf_pm_ports_dir _leaf_pm_python_shim_dir
EOF
  mv "$tmp" "$hook_path"
  chmod 755 "$hook_path" 2>/dev/null || true
}

patch_control_txt() {
  control_txt="$controlfolder/control.txt"
  [ -f "$control_txt" ] || return 0
  if grep -q 'leaf-armhf-env.sh' "$control_txt"; then
    return 0
  fi

  tmp="$control_txt.tmp.$$"
  awk '
    {
      print
      if ($0 == "source $controlfolder/funcs.txt" && inserted == 0) {
        print ""
        print "# Leaf runtime compatibility hook"
        print "if [ -f \"$controlfolder/leaf-armhf-env.sh\" ]; then"
        print "  source \"$controlfolder/leaf-armhf-env.sh\""
        print "fi"
        inserted = 1
      }
    }
    END {
      if (inserted == 0) {
        print ""
        print "# Leaf runtime compatibility hook"
        print "if [ -f \"$controlfolder/leaf-armhf-env.sh\" ]; then"
        print "  source \"$controlfolder/leaf-armhf-env.sh\""
        print "fi"
      }
    }
  ' "$control_txt" >"$tmp"
  mv "$tmp" "$control_txt"
  chmod 755 "$control_txt" 2>/dev/null || true
}

elf_header_hex() {
  od -An -tx1 -N20 "$1" 2>/dev/null | tr -d ' \n'
}

is_armhf_elf() {
  header="$1"
  [ "${#header}" -ge 40 ] || return 1
  [ "${header:0:8}" = "7f454c46" ] || return 1
  [ "${header:8:2}" = "01" ] || return 1
  [ "${header:10:2}" = "01" ] || return 1
  [ "${header:36:4}" = "2800" ] || return 1
}

elf_kind() {
  header="$1"
  case "${header:32:4}" in
    0200) printf 'executable' ;;
    0300) printf 'shared-or-pie' ;;
    *) printf 'elf-type-%s' "${header:32:4}" ;;
  esac
}

armhf_interpreter() {
  file="$1"
  grep -a -m 1 -o '/[^[:space:]]*ld-linux-armhf\.so\.3' "$file" 2>/dev/null | head -n 1 || true
}

file_sha256() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" 2>/dev/null | awk '{print $1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" 2>/dev/null | awk '{print $1}'
  else
    printf 'unknown'
  fi
}

wrapper_path_for() {
  file="$1"
  dir="$(dirname "$file")"
  base="$(basename "$file")"
  printf '%s/.leaf-armhf/%s' "$dir" "$base"
}

write_armhf_wrapper() {
  file="$1"
  original="$2"
  base="$(basename "$file")"
  quoted_original="$(shell_quote ".leaf-armhf/$base")"
  tmp="$file.tmp.$$"

  cat >"$tmp" <<EOF
#!/bin/sh
# LEAF_PM_ARMHF_WRAPPER=1
set -eu

self_dir="\$(CDPATH= cd -- "\$(dirname -- "\$0")" && pwd)"
control_dir="\${PORTMASTER_CONTROLFOLDER:-\${controlfolder:-}}"
if [ -n "\$control_dir" ] && [ -f "\$control_dir/leaf-armhf-env.sh" ]; then
  . "\$control_dir/leaf-armhf-env.sh"
fi

if [ -z "\${LEAF_PM_ARMHF_RUN:-}" ]; then
  platform="\${PLATFORM:-mlp1}"
  sdcard="\${SDCARD_PATH:-}"
  if [ -z "\$sdcard" ]; then
    if [ -d /media/sdcard1/.userdata ]; then
      sdcard="/media/sdcard1"
    else
      sdcard="/mnt/sdcard"
    fi
  fi
  userdata="\${USERDATA_PATH:-\$sdcard/.userdata/\$platform}"
  LEAF_PM_ARMHF_RUN="\${LEAF_PM_ARMHF_ROOT:-\$userdata/portmaster/compat/armhf}/bin/leaf-armhf-run"
fi

exec "\$LEAF_PM_ARMHF_RUN" "\$self_dir"/$quoted_original "\$@"
EOF
  mv "$tmp" "$file"
  chmod 755 "$file" "$original" 2>/dev/null || true
}

is_godot_script() {
  file="$1"
  case "$file" in
    *.sh) ;;
    *) return 1 ;;
  esac
  grep -Eq 'godot_runtime=|godot_executable=|--rendering-driver[[:space:]]+opengl3_es|godot[0-9]+.*DEVICE_ARCH' "$file" 2>/dev/null
}

is_gothic_machismo_script() {
  file="$1"
  case "$file" in
    *.sh) ;;
    *) return 1 ;;
  esac
  grep -Eq 'bin/machismo|MACHISMO_CONFIG' "$file" 2>/dev/null &&
    grep -Eq 'GOTHIC_BACKEND|GOTHIC_SHADER_DIR|libgothic_patches' "$file" 2>/dev/null
}

normalize_port_env_script() {
  file="$1"
  case "$file" in
    *.sh) ;;
    *) printf 'not-shell'; return 0 ;;
  esac
  if grep -q 'LEAF_PM_PORT_ENV=1' "$file" 2>/dev/null; then
    printf 'port-env-already'
    return 0
  fi

  tmp="$file.tmp.$$"
  awk '
    function insert_block() {
      print ""
      print "# LEAF_PM_PORT_ENV=1"
      print "_leaf_pm_platform=\"${PLATFORM:-mlp1}\""
      print "if [ -z \"${XDG_DATA_HOME:-}\" ] || [ ! -d \"$XDG_DATA_HOME/PortMaster\" ]; then"
      print "  for _leaf_pm_sd in \"${SDCARD_PATH:-}\" \"${JAWAKA_SDCARD_ROOT:-}\" /media/sdcard1 /mnt/sdcard; do"
      print "    [ -n \"$_leaf_pm_sd\" ] || continue"
      print "    _leaf_pm_userdata=\"${USERDATA_PATH:-$_leaf_pm_sd/.userdata/$_leaf_pm_platform}\""
      print "    if [ -d \"$_leaf_pm_userdata/portmaster/PortMaster\" ]; then"
      print "      export SDCARD_PATH=\"${SDCARD_PATH:-$_leaf_pm_sd}\""
      print "      export USERDATA_PATH=\"$_leaf_pm_userdata\""
      print "      export ROMS_PATH=\"${ROMS_PATH:-$SDCARD_PATH/Roms}\""
      print "      export IMAGES_PATH=\"${IMAGES_PATH:-$SDCARD_PATH/Images}\""
      print "      export XDG_DATA_HOME=\"$_leaf_pm_userdata/portmaster\""
      print "      export PORTMASTER_CONTROLFOLDER=\"$_leaf_pm_userdata/portmaster/PortMaster\""
      print "      break"
      print "    fi"
      print "  done"
      print "fi"
      print "unset _leaf_pm_sd _leaf_pm_userdata _leaf_pm_platform"
      inserted = 1
    }
    {
      print
      if (!inserted && $0 ~ /^XDG_DATA_HOME=/) {
        insert_block()
      } else if (!inserted && $0 ~ /source[[:space:]]+\$?controlfolder\/control[.]txt/) {
        insert_block()
      }
    }
    END {
      if (!inserted) {
        insert_block()
      }
    }
  ' "$file" >"$tmp"
  mv "$tmp" "$file"
  chmod 755 "$file" 2>/dev/null || true
  printf 'port-env-patched'
}

normalize_port_paths_script() {
  file="$1"
  case "$file" in
    *.sh) ;;
    *) printf 'not-shell'; return 0 ;;
  esac
  if ! grep -q 'GAMEDIR=/\$directory/ports/' "$file" 2>/dev/null; then
    printf 'port-paths-already'
    return 0
  fi

  tmp="$file.tmp.$$"
  awk '
    /^[[:space:]]*GAMEDIR=\/\$directory\/ports\/[^[:space:]#]+[[:space:]]*$/ {
      line = $0
      sub(/GAMEDIR=\/\$directory\/ports\//, "GAMEDIR=\"${HM_PORTS_DIR:-/$directory/ports}/", line)
      print line "\""
      next
    }
    { print }
  ' "$file" >"$tmp"
  mv "$tmp" "$file"
  chmod 755 "$file" 2>/dev/null || true
  printf 'port-paths-patched'
}

normalize_godot_wayland_script() {
  file="$1"
  if ! is_godot_script "$file"; then
    printf 'not-godot'
    return 0
  fi
  if grep -Eq 'LEAF_PM_(GODOT_WAYLAND|EGL_GLES_SHIM)=1' "$file" 2>/dev/null; then
    printf 'godot-wayland-already'
    return 0
  fi

  tmp="$file.tmp.$$"
  awk '
    function insert_block() {
      print ""
      print "# LEAF_PM_GODOT_WAYLAND=1"
      print "if declare -f leaf_pm_enable_godot_wayland_runtime >/dev/null 2>&1; then"
      print "  leaf_pm_enable_godot_wayland_runtime"
      print "fi"
      inserted = 1
    }
    {
      print
      if (!inserted && $0 ~ /^[[:space:]]*get_controls([[:space:]]|$)/) {
        insert_block()
      } else if (!inserted && $0 ~ /source[[:space:]].*control[.]txt/) {
        insert_block()
      }
    }
    END {
      if (!inserted) {
        insert_block()
      }
    }
  ' "$file" >"$tmp"
  mv "$tmp" "$file"
  chmod 755 "$file" 2>/dev/null || true
  printf 'godot-wayland-patched'
}

normalize_godot_weston_cleanup_script() {
  file="$1"
  if ! is_godot_script "$file"; then
    printf 'not-godot'
    return 0
  fi
  if grep -q 'LEAF_PM_WESTONPACK_CLEANUP_GUARD=1' "$file" 2>/dev/null; then
    printf 'weston-cleanup-already'
    return 0
  fi

  tmp="$file.tmp.$$"
  awk '
    /^[[:space:]]*#/ { print; next }
    index($0, "westonwrap.sh cleanup") > 0 {
      indent = $0
      sub(/[^[:space:]].*$/, "", indent)
      cmd = substr($0, length(indent) + 1)
      print indent "# LEAF_PM_WESTONPACK_CLEANUP_GUARD=1"
      print indent "if [ \"${LEAF_PM_SKIP_WESTONPACK_CLEANUP:-0}\" != \"1\" ]; then"
      print indent "  " cmd
      print indent "fi"
      changed = 1
      next
    }
    { print }
    END {
      if (!changed) {
        exit 2
      }
    }
  ' "$file" >"$tmp"
  rc=$?
  if [ "$rc" -eq 2 ]; then
    rm -f "$tmp"
    printf 'weston-cleanup-missing'
    return 0
  fi
  if [ "$rc" -ne 0 ]; then
    rm -f "$tmp"
    printf 'weston-cleanup-error'
    return 0
  fi
  mv "$tmp" "$file"
  chmod 755 "$file" 2>/dev/null || true
  printf 'weston-cleanup-patched'
}

runtime_compat_gothic_machismo_gles_script() {
  file="$1"
  if ! is_gothic_machismo_script "$file"; then
    printf 'not-gothic-machismo'
    return 0
  fi
  if grep -Eq 'LEAF_PM_(RUNTIME_COMPAT_GOTHIC_MACHISMO_GLES|MINA_GLES)=1' "$file" 2>/dev/null; then
    printf 'runtime-compat-gothic-machismo-gles-already'
    return 0
  fi

  tmp="$file.tmp.$$"
  awk '
    function insert_block() {
      print ""
      print "# LEAF_PM_RUNTIME_COMPAT_GOTHIC_MACHISMO_GLES=1"
      print "# MLP1 stock Vulkan lacks Wayland WSI for Gothic/Machismo ports; avoid the raw 720x960 direct-display fallback."
      print "if [ \"${CFW_NAME:-}\" = \"Leaf\" ]; then"
      print "  export GOTHIC_BACKEND=\"${GOTHIC_BACKEND:-gles}\""
      print "fi"
      inserted = 1
    }
    {
      print
      if (!inserted && $0 ~ /^[[:space:]]*get_controls([[:space:]]|$)/) {
        insert_block()
      } else if (!inserted && $0 ~ /source[[:space:]].*control[.]txt/) {
        insert_block()
      }
    }
    END {
      if (!inserted) {
        insert_block()
      }
    }
  ' "$file" >"$tmp"
  mv "$tmp" "$file"
  chmod 755 "$file" 2>/dev/null || true
  printf 'runtime-compat-gothic-machismo-gles-patched'
}

apply_runtime_compat_rules_script() {
  file="$1"
  case "$file" in
    *.sh) ;;
    *) return 0 ;;
  esac

  if is_gothic_machismo_script "$file"; then
    runtime_compat_gothic_machismo_gles_script "$file"
    printf '\n'
  fi
}

find_shell_script_candidates() {
  find "$ports_dir" -type f -name '*.sh' ! -path '*/.leaf-armhf/*' -print0
}

find_elf_candidates() {
  if [ "$scan_mode" = "full" ]; then
    find "$ports_dir" -type f ! -path '*/.leaf-armhf/*' -print0
    return 0
  fi

  ports_root="${ports_dir%/}"
  find "$ports_dir" -type f ! -path '*/.leaf-armhf/*' ! -name '*.sh' \
    \( \
      \( -path "$ports_root/*/*" ! -path "$ports_root/*/*/*" \) -o \
      -path '*/bin/*' -o \
      -path '*/box86/*' -o \
      -path '*/libs/*' -o \
      -path '*/lib/*' -o \
      -name '*.so' -o \
      -name '*.so.*' \
    \) -print0
}

normalize_armhf_executable() {
  file="$1"
  [ "$compat_available" -eq 1 ] || {
    printf 'needs-wrapper-compat-missing'
    return 0
  }

  original="$(wrapper_path_for "$file")"
  mkdir -p "$(dirname "$original")"
  if [ -f "$original" ]; then
    printf 'already-normalized'
    return 0
  fi

  mv "$file" "$original"
  write_armhf_wrapper "$file" "$original"
  printf 'wrapped'
}

write_leaf_hook
patch_control_txt

tmp_records="$report_tsv.tmp.$$"
printf 'path\tkind\tinterpreter\tsha256\taction\n' >"$tmp_records"

seen=0
shell_scripts_seen=0
wrapped=0
shared=0
needs_wrapper=0
already=0
errors=0
godot_patched=0
godot_already=0
weston_cleanup_patched=0
weston_cleanup_already=0
weston_cleanup_missing=0
port_env_patched=0
port_env_already=0
port_paths_patched=0
port_paths_already=0
runtime_compat_gothic_machismo_gles_patched=0
runtime_compat_gothic_machismo_gles_already=0

while IFS= read -r -d '' file; do
  shell_scripts_seen=$((shell_scripts_seen + 1))

  case "$(normalize_port_env_script "$file")" in
    port-env-patched) port_env_patched=$((port_env_patched + 1)) ;;
    port-env-already) port_env_already=$((port_env_already + 1)) ;;
  esac

  case "$(normalize_port_paths_script "$file")" in
    port-paths-patched) port_paths_patched=$((port_paths_patched + 1)) ;;
    port-paths-already) port_paths_already=$((port_paths_already + 1)) ;;
  esac

  case "$(normalize_godot_wayland_script "$file")" in
    godot-wayland-patched) godot_patched=$((godot_patched + 1)) ;;
    godot-wayland-already) godot_already=$((godot_already + 1)) ;;
  esac

  case "$(normalize_godot_weston_cleanup_script "$file")" in
    weston-cleanup-patched) weston_cleanup_patched=$((weston_cleanup_patched + 1)) ;;
    weston-cleanup-already) weston_cleanup_already=$((weston_cleanup_already + 1)) ;;
    weston-cleanup-missing) weston_cleanup_missing=$((weston_cleanup_missing + 1)) ;;
  esac

  while IFS= read -r runtime_compat_action; do
    case "$runtime_compat_action" in
      runtime-compat-gothic-machismo-gles-patched)
        runtime_compat_gothic_machismo_gles_patched=$((runtime_compat_gothic_machismo_gles_patched + 1))
        ;;
      runtime-compat-gothic-machismo-gles-already)
        runtime_compat_gothic_machismo_gles_already=$((runtime_compat_gothic_machismo_gles_already + 1))
        ;;
    esac
  done < <(apply_runtime_compat_rules_script "$file")
done < <(find_shell_script_candidates)

while IFS= read -r -d '' file; do
  header="$(elf_header_hex "$file")"
  if ! is_armhf_elf "$header"; then
    if head -n 3 "$file" 2>/dev/null | grep -q 'LEAF_PM_ARMHF_WRAPPER=1'; then
      already=$((already + 1))
      sha="$(file_sha256 "$file")"
      printf '%s\t%s\t%s\t%s\t%s\n' "$file" "wrapper" "" "$sha" "wrapper-present" >>"$tmp_records"
    fi
    continue
  fi

  seen=$((seen + 1))
  kind="$(elf_kind "$header")"
  interpreter="$(armhf_interpreter "$file")"
  sha="$(file_sha256 "$file")"
  action="observed"

  if [ -n "$interpreter" ]; then
    if action="$(normalize_armhf_executable "$file")"; then
      case "$action" in
        wrapped) wrapped=$((wrapped + 1)) ;;
        already-normalized) already=$((already + 1)) ;;
        needs-wrapper-compat-missing) needs_wrapper=$((needs_wrapper + 1)) ;;
      esac
    else
      action="error"
      errors=$((errors + 1))
    fi
  else
    shared=$((shared + 1))
    action="shared-object"
  fi

  printf '%s\t%s\t%s\t%s\t%s\n' "$file" "$kind" "$interpreter" "$sha" "$action" >>"$tmp_records"
done < <(find_elf_candidates)

mv "$tmp_records" "$report_tsv"

tmp_json="$report_json.tmp.$$"
cat >"$tmp_json" <<EOF
{
  "schema": 1,
  "platform": "$(json_escape "$platform")",
  "ports_dir": "$(json_escape "$ports_dir")",
  "scan_mode": "$(json_escape "$scan_mode")",
  "controlfolder": "$(json_escape "$controlfolder")",
  "compat_root": "$(json_escape "$compat_root")",
  "compat_available": $([ "$compat_available" -eq 1 ] && printf 'true' || printf 'false'),
  "hook": "$(json_escape "$hook_path")",
  "records_tsv": "$(json_escape "$report_tsv")",
  "armhf_elfs_seen": $seen,
  "armhf_execs_wrapped": $wrapped,
  "armhf_execs_already_normalized": $already,
  "armhf_execs_needing_compat": $needs_wrapper,
  "armhf_shared_objects_seen": $shared,
  "shell_scripts_seen": $shell_scripts_seen,
  "port_env_scripts_patched": $port_env_patched,
  "port_env_scripts_already_patched": $port_env_already,
  "port_path_scripts_patched": $port_paths_patched,
  "port_path_scripts_already_patched": $port_paths_already,
  "godot_wayland_scripts_patched": $godot_patched,
  "godot_wayland_scripts_already_patched": $godot_already,
  "godot_weston_cleanup_scripts_patched": $weston_cleanup_patched,
  "godot_weston_cleanup_scripts_already_patched": $weston_cleanup_already,
  "godot_weston_cleanup_scripts_missing_cleanup": $weston_cleanup_missing,
  "runtime_compat_gothic_machismo_gles_scripts_patched": $runtime_compat_gothic_machismo_gles_patched,
  "runtime_compat_gothic_machismo_gles_scripts_already_patched": $runtime_compat_gothic_machismo_gles_already,
  "godot_egl_scripts_patched": $godot_patched,
  "godot_egl_scripts_already_patched": $godot_already,
  "errors": $errors
}
EOF
mv "$tmp_json" "$report_json"

log "mode=$scan_mode scripts=$shell_scripts_seen seen=$seen wrapped=$wrapped shared=$shared needs_compat=$needs_wrapper port_env_patched=$port_env_patched port_paths_patched=$port_paths_patched godot_patched=$godot_patched weston_cleanup_patched=$weston_cleanup_patched runtime_compat_gothic_machismo_gles_patched=$runtime_compat_gothic_machismo_gles_patched report=$report_tsv"
