#!/usr/bin/env bash
set -euo pipefail

platform="${PLATFORM:-mlp1}"
sdcard_path="${SDCARD_PATH:-}"
if [ -z "$sdcard_path" ]; then
  for candidate in /mnt/sdcard /media/sdcard1; do
    if [ -f "$candidate/.system/leaf/platforms/$platform/enabled" ]; then
      sdcard_path="$candidate"
      break
    fi
  done
fi
if [ -z "$sdcard_path" ]; then
  for candidate in /mnt/sdcard /media/sdcard1; do
    if [ -d "$candidate/.userdata/$platform/portmaster" ]; then
      sdcard_path="$candidate"
      break
    fi
  done
fi
sdcard_path="${sdcard_path:-/mnt/sdcard}"

userdata_path="${USERDATA_PATH:-$sdcard_path/.userdata/$platform}"
data_dir="${PORTMASTER_MLP1_DATA_DIR:-$userdata_path/portmaster}"
controlfolder="${PORTMASTER_CONTROLFOLDER:-$data_dir/PortMaster}"
hook_path="${1:-$controlfolder/leaf-armhf-env.sh}"
hook_dir="$(dirname -- "$hook_path")"

controller_x360="1900fe3c039900001399000002010000,Loong Gamepad,a:b0,b:b1,x:b3,y:b2,back:b8,guide:b10,start:b9,leftstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,lefttrigger:b6,righttrigger:b7,crc:3cfe,platform:Linux"
controller_gui="1900fe3c039900001399000002010000,Loong Gamepad,a:b1,b:b0,x:b3,y:b2,back:b8,guide:b10,start:b9,leftstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,lefttrigger:b6,righttrigger:b7,crc:3cfe,platform:Linux"
controller_nintendo="1900fe3c039900001399000002010000,Loong Gamepad,a:b1,b:b0,x:b2,y:b3,back:b8,guide:b10,start:b9,leftstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,lefttrigger:b6,righttrigger:b7,crc:3cfe,platform:Linux"

if [ ! -d "$hook_dir" ]; then
  echo "Leaf PortMaster hook dir missing: $hook_dir" >&2
  exit 1
fi

tmp="$hook_path.tmp.$$"
trap 'rm -f "$tmp"' EXIT HUP INT TERM

cat >"$tmp" <<EOF
#!/bin/sh
# Generated by PortMaster-mlp1. Safe to overwrite.

_leaf_pm_controlfolder="\${controlfolder:-\${PORTMASTER_CONTROLFOLDER:-$controlfolder}}"
if [ -n "\$_leaf_pm_controlfolder" ] && [ -d "\$_leaf_pm_controlfolder/.." ]; then
  _leaf_pm_data_dir="\$(CDPATH= cd -- "\$_leaf_pm_controlfolder/.." && pwd)"
else
  _leaf_pm_data_dir="$data_dir"
fi
export LEAF_PM_DATA_DIR="\$_leaf_pm_data_dir"
export PLATFORM="\${PLATFORM:-$platform}"
if [ -z "\${SDCARD_PATH:-}" ]; then
  case "\$LEAF_PM_DATA_DIR" in
    */.userdata/*/portmaster) export SDCARD_PATH="\${LEAF_PM_DATA_DIR%%/.userdata/*}" ;;
  esac
fi
export PORTMASTER_CONTROLFOLDER="\${PORTMASTER_CONTROLFOLDER:-\$_leaf_pm_controlfolder}"
export PORTMASTER_LEAF_DEVICE_INFO="\${PORTMASTER_LEAF_DEVICE_INFO:-1}"
export HOME="\$LEAF_PM_DATA_DIR"
export XDG_DATA_HOME="\$LEAF_PM_DATA_DIR"
export HM_TOOLS_DIR="\${HM_TOOLS_DIR:-\$LEAF_PM_DATA_DIR}"
if [ -n "\${ROMS_PATH:-}" ]; then
  _leaf_pm_roms_dir="\${ROMS_PATH%/}"
  _leaf_pm_ports_dir="\$ROMS_PATH/PORTS"
elif [ -n "\${SDCARD_PATH:-}" ]; then
  _leaf_pm_roms_dir="\${SDCARD_PATH%/}/Roms"
  _leaf_pm_ports_dir="\$SDCARD_PATH/Roms/PORTS"
else
  _leaf_pm_roms_dir=""
  _leaf_pm_ports_dir="/\${directory:-roms}/ports"
fi
if [ -n "\$_leaf_pm_roms_dir" ] &&
   ! awk '\$2 == "/roms/ports" { found = 1 } END { exit found ? 0 : 1 }' /proc/mounts 2>/dev/null; then
  export directory="\${_leaf_pm_roms_dir#/}"
fi
export HM_PORTS_DIR="\${HM_PORTS_DIR:-\$_leaf_pm_ports_dir}"
export HM_SCRIPTS_DIR="\${HM_SCRIPTS_DIR:-\$HM_PORTS_DIR}"

_leaf_pm_system_dir="\${UMRK_PLATFORM_PATH:-}"
if [ -z "\$_leaf_pm_system_dir" ] && [ -n "\${SDCARD_PATH:-}" ]; then
  _leaf_pm_system_dir="\${SDCARD_PATH%/}/.system/leaf/platforms/\${PLATFORM:-mlp1}"
fi
_leaf_pm_internal_dir=""
if [ -n "\${SDCARD_PATH:-}" ]; then
  _leaf_pm_internal_dir="\${SDCARD_PATH%/}/.umrk/\${PLATFORM:-mlp1}"
fi
export LEAF_PM_RETROARCH_BIN="\${LEAF_PM_RETROARCH_BIN:-\${UMRK_RETROARCH_BIN:-\${JAWAKA_RETROARCH_BIN:-}}}"
if [ -z "\$LEAF_PM_RETROARCH_BIN" ] && [ -x "\$_leaf_pm_system_dir/bin/retroarch" ]; then
  export LEAF_PM_RETROARCH_BIN="\$_leaf_pm_system_dir/bin/retroarch"
fi
export LEAF_PM_RETROARCH_CONFIG="\${LEAF_PM_RETROARCH_CONFIG:-\${UMRK_RETROARCH_CONFIG:-\${JAWAKA_RETROARCH_CONFIG:-}}}"
if [ -z "\$LEAF_PM_RETROARCH_CONFIG" ] && [ -f "\$_leaf_pm_internal_dir/retroarch/retroarch.cfg" ]; then
  export LEAF_PM_RETROARCH_CONFIG="\$_leaf_pm_internal_dir/retroarch/retroarch.cfg"
elif [ -z "\$LEAF_PM_RETROARCH_CONFIG" ] && [ -f "\$_leaf_pm_system_dir/defaults/retroarch.cfg" ]; then
  export LEAF_PM_RETROARCH_CONFIG="\$_leaf_pm_system_dir/defaults/retroarch.cfg"
fi
leaf_pm_run_retroarch() {
  _leaf_pm_ra_bin="\${LEAF_PM_RETROARCH_BIN:-}"
  if [ -z "\$_leaf_pm_ra_bin" ]; then
    _leaf_pm_ra_bin="\$(command -v retroarch 2>/dev/null || true)"
  fi
  if [ -z "\$_leaf_pm_ra_bin" ] || [ ! -x "\$_leaf_pm_ra_bin" ]; then
    echo "Leaf PortMaster: RetroArch binary missing" >&2
    return 127
  fi
  if [ -n "\${LEAF_PM_RETROARCH_CONFIG:-}" ] && [ -f "\$LEAF_PM_RETROARCH_CONFIG" ]; then
    "\$_leaf_pm_ra_bin" --config "\$LEAF_PM_RETROARCH_CONFIG" "\$@"
  else
    "\$_leaf_pm_ra_bin" "\$@"
  fi
}

export LEAF_PM_TOOLS_DIR="\${LEAF_PM_TOOLS_DIR:-\$LEAF_PM_DATA_DIR/compat/tools/aarch64/bin}"
if [ -d "\$LEAF_PM_TOOLS_DIR" ]; then
  case ":\${PATH:-}:" in
    *:"\$LEAF_PM_TOOLS_DIR":*) ;;
    *) export PATH="\$LEAF_PM_TOOLS_DIR:\${PATH:-/usr/bin:/usr/sbin:/bin:/sbin}" ;;
  esac
fi

export LEAF_PM_EGL_SHIM_DIR="\${LEAF_PM_EGL_SHIM_DIR:-\$LEAF_PM_DATA_DIR/compat/egl/aarch64}"
export LEAF_PM_MALI_AARCH64_DIR="\${LEAF_PM_MALI_AARCH64_DIR:-\$LEAF_PM_DATA_DIR/compat/mali/aarch64}"
leaf_pm_prepare_godot_runtime_env() {
  [ "\${DEVICE_ARCH:-aarch64}" = "aarch64" ] || return 0
  export LEAF_PM_SKIP_WESTONPACK_CLEANUP="\${LEAF_PM_SKIP_WESTONPACK_CLEANUP:-1}"
  _leaf_pm_wayland_runtime="\${LEAF_PM_WAYLAND_RUNTIME_DIR:-\${XDG_RUNTIME_DIR:-/var/run}}"
  _leaf_pm_wayland_display="\${LEAF_PM_WAYLAND_DISPLAY:-\${WAYLAND_DISPLAY:-wayland-0}}"
  _leaf_pm_egl_shim="\${LEAF_PM_EGL_SHIM_DIR:-}/libEGL.so.1"
  if [ -f "\${LEAF_PM_MALI_AARCH64_DIR:-}/libmali.so.1" ]; then
    export LEAF_PM_MALI_LIB="\$LEAF_PM_MALI_AARCH64_DIR/libmali.so.1"
    case ":\${LD_LIBRARY_PATH:-}:" in
      *:"\$LEAF_PM_MALI_AARCH64_DIR":*) ;;
      *) export LD_LIBRARY_PATH="\$LEAF_PM_MALI_AARCH64_DIR\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}" ;;
    esac
  fi
  if [ -f "\$_leaf_pm_egl_shim" ]; then
    case ":\${LD_LIBRARY_PATH:-}:" in
      *:"\$LEAF_PM_EGL_SHIM_DIR":*) ;;
      *) export LD_LIBRARY_PATH="\$LEAF_PM_EGL_SHIM_DIR\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}" ;;
    esac
  fi
  export XDG_RUNTIME_DIR="\$_leaf_pm_wayland_runtime"
  export WAYLAND_DISPLAY="\$_leaf_pm_wayland_display"
  export SDL_VIDEODRIVER=wayland
}

leaf_pm_args_have_display_driver() {
  while [ "\$#" -gt 0 ]; do
    case "\$1" in
      --display-driver|--display-driver=*) return 0 ;;
    esac
    shift
  done
  return 1
}

leaf_pm_args_have_window_mode() {
  while [ "\$#" -gt 0 ]; do
    case "\$1" in
      -f|--fullscreen|--fullscreen=*|-w|--windowed|--windowed=*|--resolution|--resolution=*|--position|--position=*) return 0 ;;
    esac
    shift
  done
  return 1
}

leaf_pm_run_godot_wayland_runtime() {
  [ "\$#" -gt 0 ] || return 127
  _leaf_pm_godot_cmd="\$1"
  shift
  leaf_pm_prepare_godot_runtime_env
  if leaf_pm_args_have_display_driver "\$@"; then
    "\$_leaf_pm_godot_cmd" "\$@"
    return \$?
  fi
  "\$_leaf_pm_godot_cmd" --display-driver wayland "\$@"
}

leaf_pm_run_godot_sdl2_runtime() {
  [ "\$#" -gt 0 ] || return 127
  _leaf_pm_godot_cmd="\$1"
  shift
  leaf_pm_prepare_godot_runtime_env
  _leaf_pm_direct_resolution="\${LEAF_PM_GODOT_DIRECT_RESOLUTION:-960x720}"
  if [ -n "\$_leaf_pm_direct_resolution" ] && ! leaf_pm_args_have_window_mode "\$@"; then
    "\$_leaf_pm_godot_cmd" --resolution "\$_leaf_pm_direct_resolution" "\$@"
    return \$?
  fi
  "\$_leaf_pm_godot_cmd" "\$@"
}

leaf_pm_enable_godot_wayland_runtime() {
  _leaf_pm_env_bin="\$(command -v env 2>/dev/null || printf '%s\n' /usr/bin/env)"
  env() {
    if [ "\${1##*/}" = "westonwrap.sh" ] && [ "\${2:-}" != "cleanup" ] && [ "\$#" -ge 6 ]; then
      # MLP1 already has Leaf's Weston running; PortMaster's nested Westonpack
      # wrapper cannot provide the EGL display Godot 4 expects on stock firmware.
      shift
      shift 4
      while [ "\$#" -gt 0 ]; do
        case "\$1" in
          *=*) export "\$1"; shift ;;
          *) break ;;
        esac
      done
      [ "\$#" -gt 0 ] || return 127
      _leaf_pm_godot_cmd="\$1"
      shift
      leaf_pm_run_godot_wayland_runtime "\$_leaf_pm_godot_cmd" "\$@"
      return \$?
    fi
    "\$_leaf_pm_env_bin" "\$@"
  }
}

leaf_pm_enable_egl_gles_shim() {
  leaf_pm_enable_godot_wayland_runtime "\$@"
}

export LEAF_PM_RUNTIME_DIR="\${LEAF_PM_RUNTIME_DIR:-\$LEAF_PM_DATA_DIR/runtime}"
if [ -x "\$LEAF_PM_RUNTIME_DIR/bin/python3" ]; then
  _leaf_pm_python_shim_dir="/tmp/leaf-portmaster-python"
  if mkdir -p "\$_leaf_pm_python_shim_dir" 2>/dev/null; then
    cat >"\$_leaf_pm_python_shim_dir/python3" <<'LEAF_PM_PYTHON_SHIM'
#!/bin/sh
_runtime="\${LEAF_PM_RUNTIME_DIR:-}"
if [ -z "\$_runtime" ] || [ ! -x "\$_runtime/bin/python3" ]; then
  echo "Leaf PortMaster python runtime missing" >&2
  exit 127
fi
if [ -n "\${LD_LIBRARY_PATH:-}" ]; then
  export LD_LIBRARY_PATH="\$_runtime/lib:\$LD_LIBRARY_PATH"
else
  export LD_LIBRARY_PATH="\$_runtime/lib"
fi
export PYTHONHOME="\$_runtime"
export PYTHONPATH="\$_runtime/lib/python3.10:\$_runtime/lib/python3.10/site-packages:\$_runtime/lib\${PYTHONPATH:+:\$PYTHONPATH}"
export PYTHONDONTWRITEBYTECODE="\${PYTHONDONTWRITEBYTECODE:-1}"
exec "\$_runtime/bin/python3" "\$@"
LEAF_PM_PYTHON_SHIM
    chmod 755 "\$_leaf_pm_python_shim_dir/python3" 2>/dev/null || true
    cp -f "\$_leaf_pm_python_shim_dir/python3" "\$_leaf_pm_python_shim_dir/python" 2>/dev/null || true
    case ":\${PATH:-}:" in
      *:"\$_leaf_pm_python_shim_dir":*) ;;
      *) export PATH="\$_leaf_pm_python_shim_dir:\${PATH:-/usr/bin:/usr/sbin}" ;;
    esac
  fi
fi

leaf_pm_apply_controller_layout() {
  if [ "\${PORTMASTER_LEAF_PORT_LAYOUT_SCOPE:-ports}" = "gui" ]; then
    export PORTMASTER_LEAF_CONTROLLER_LAYOUT="gui"
    export SDL_GAMECONTROLLERCONFIG='$controller_gui'
  elif [ -f "\$LEAF_PM_DATA_DIR/nintendo" ]; then
    export PORTMASTER_LEAF_CONTROLLER_LAYOUT="nintendo"
    export SDL_GAMECONTROLLERCONFIG='$controller_nintendo'
  else
    export PORTMASTER_LEAF_CONTROLLER_LAYOUT="x360"
    export SDL_GAMECONTROLLERCONFIG='$controller_x360'
  fi
  export sdl_controllerconfig="\$SDL_GAMECONTROLLERCONFIG"
  export SDL_GAMECONTROLLERCONFIG_FILE="/tmp/leaf-portmaster-gamecontrollerdb.txt"
  printf '%s\n' "\$SDL_GAMECONTROLLERCONFIG" >"\$SDL_GAMECONTROLLERCONFIG_FILE" 2>/dev/null || true
}

if declare -f get_controls >/dev/null 2>&1; then
  if ! declare -f leaf_pm_upstream_get_controls >/dev/null 2>&1; then
    eval "\$(declare -f get_controls | sed '1s/get_controls/leaf_pm_upstream_get_controls/')"
  fi
  get_controls() {
    leaf_pm_upstream_get_controls "\$@"
    leaf_pm_apply_controller_layout
  }
fi

leaf_pm_apply_controller_layout

export DEVICE_HAS_ARMHF="\${DEVICE_HAS_ARMHF:-N}"
export DEVICE_HAS_AARCH64="\${DEVICE_HAS_AARCH64:-Y}"

export LEAF_PM_ARMHF_ROOT="\${LEAF_PM_ARMHF_ROOT:-\$LEAF_PM_DATA_DIR/compat/armhf}"
if [ -f "\$LEAF_PM_ARMHF_ROOT/lib/ld-linux-armhf.so.3" ] && [ -f "\$LEAF_PM_ARMHF_ROOT/bin/leaf-armhf-run" ]; then
  export DEVICE_HAS_ARMHF="Y"
  export LEAF_PM_ARMHF_LOADER="\$LEAF_PM_ARMHF_ROOT/lib/ld-linux-armhf.so.3"
  export LEAF_PM_ARMHF_RUN="\$LEAF_PM_ARMHF_ROOT/bin/leaf-armhf-run"
  export LEAF_PM_ARMHF_LIB_PATH="\$LEAF_PM_ARMHF_ROOT/usr/lib/arm-linux-gnueabihf/mali:\$LEAF_PM_ARMHF_ROOT/lib/arm-linux-gnueabihf:\$LEAF_PM_ARMHF_ROOT/usr/lib/arm-linux-gnueabihf:\$LEAF_PM_ARMHF_ROOT/usr/lib/arm-linux-gnueabihf/pulseaudio:\$LEAF_PM_ARMHF_ROOT/lib:\$LEAF_PM_ARMHF_ROOT/usr/lib"
  export LEAF_PM_ARMHF_SDL_VIDEO_EGL_DRIVER="\${LEAF_PM_ARMHF_SDL_VIDEO_EGL_DRIVER:-libEGL.so}"
  export LEAF_PM_ARMHF_SDL_VIDEO_GL_DRIVER="\${LEAF_PM_ARMHF_SDL_VIDEO_GL_DRIVER:-libGLESv2.so}"
  export SDL_VIDEO_EGL_DRIVER="\${SDL_VIDEO_EGL_DRIVER:-\$LEAF_PM_ARMHF_SDL_VIDEO_EGL_DRIVER}"
  export SDL_VIDEO_GL_DRIVER="\${SDL_VIDEO_GL_DRIVER:-\$LEAF_PM_ARMHF_SDL_VIDEO_GL_DRIVER}"
  if [ -x "\$LEAF_PM_ARMHF_ROOT/bin/box86" ]; then
    export LEAF_PM_BOX86="\$LEAF_PM_ARMHF_ROOT/bin/box86"
  fi

  leaf_pm_armhf_run() {
    "\$LEAF_PM_ARMHF_RUN" "\$@"
  }
fi

unset _leaf_pm_controlfolder _leaf_pm_data_dir _leaf_pm_roms_dir _leaf_pm_ports_dir _leaf_pm_system_dir _leaf_pm_internal_dir _leaf_pm_python_shim_dir
EOF

chmod 755 "$tmp"
mv "$tmp" "$hook_path"
trap - EXIT HUP INT TERM
