#!/usr/bin/env bash
set -euo pipefail

platform="${PLATFORM:-mlp1}"
script_dir="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
resolver="$script_dir/resolve-sdcard-root.sh"
if [ ! -f "$resolver" ]; then
  echo "Leaf PortMaster SD resolver missing: $resolver" >&2
  exit 1
fi
if ! sdcard_path="$(PLATFORM="$platform" "$resolver" "$script_dir/.." 2>&1)"; then
  echo "Leaf PortMaster SD root error: $sdcard_path" >&2
  exit 1
fi

userdata_path="${USERDATA_PATH:-$sdcard_path/.userdata/$platform}"
data_dir="${PORTMASTER_MLP1_DATA_DIR:-$userdata_path/portmaster}"
controlfolder="${PORTMASTER_CONTROLFOLDER:-$data_dir/PortMaster}"
hook_path="${1:-$controlfolder/leaf-armhf-env.sh}"
hook_dir="$(dirname -- "$hook_path")"

controller_x360="1900fe3c039900001399000002010000,Loong Gamepad,a:b0,b:b1,x:b3,y:b2,back:b8,guide:b10,start:b9,leftstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,lefttrigger:b6,righttrigger:b7,crc:3cfe,platform:Linux"
controller_gui="1900fe3c039900001399000002010000,Loong Gamepad,a:b1,b:b0,x:b3,y:b2,back:b8,guide:b10,start:b9,leftstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,lefttrigger:b6,righttrigger:b7,crc:3cfe,platform:Linux"
controller_nintendo="1900fe3c039900001399000002010000,Loong Gamepad,a:b1,b:b0,x:b2,y:b3,back:b8,guide:b10,start:b9,leftstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,lefttrigger:b6,righttrigger:b7,crc:3cfe,platform:Linux"

if [ ! -d "$hook_dir" ]; then
  echo "Leaf PortMaster hook dir missing: $hook_dir" >&2
  exit 1
fi

tmp_root="${TMPDIR:-/tmp}"
[ -d "$tmp_root" ] || tmp_root="$hook_dir"
tmp="$tmp_root/leaf-armhf-env.$$"
install_tmp="$hook_path.tmp.$$"
trap 'rm -f "$tmp" "$install_tmp"' EXIT HUP INT TERM

cat >"$tmp" <<EOF
#!/bin/sh
# Generated by PortMaster-mlp1. Safe to overwrite.

_leaf_pm_controlfolder="\${controlfolder:-\${PORTMASTER_CONTROLFOLDER:-$controlfolder}}"
if [ -n "\$_leaf_pm_controlfolder" ] && [ -d "\$_leaf_pm_controlfolder/.." ]; then
  _leaf_pm_data_dir="\$(CDPATH= cd -- "\$_leaf_pm_controlfolder/.." && pwd)"
else
  _leaf_pm_data_dir="$data_dir"
fi
export LEAF_PM_DATA_DIR="\$_leaf_pm_data_dir"
export PLATFORM="\${PLATFORM:-$platform}"
if [ -z "\${SDCARD_PATH:-}" ]; then
  case "\$LEAF_PM_DATA_DIR" in
    */.userdata/*/portmaster) export SDCARD_PATH="\${LEAF_PM_DATA_DIR%%/.userdata/*}" ;;
  esac
fi
export PORTMASTER_CONTROLFOLDER="\${PORTMASTER_CONTROLFOLDER:-\$_leaf_pm_controlfolder}"
export PORTMASTER_LEAF_DEVICE_INFO="\${PORTMASTER_LEAF_DEVICE_INFO:-1}"
export HOME="\$LEAF_PM_DATA_DIR"
export XDG_DATA_HOME="\$LEAF_PM_DATA_DIR"
export HM_TOOLS_DIR="\${HM_TOOLS_DIR:-\$LEAF_PM_DATA_DIR}"
if [ -n "\${ROMS_PATH:-}" ]; then
  _leaf_pm_roms_dir="\${ROMS_PATH%/}"
  _leaf_pm_ports_dir="\$ROMS_PATH/PORTS"
elif [ -n "\${SDCARD_PATH:-}" ]; then
  _leaf_pm_roms_dir="\${SDCARD_PATH%/}/Roms"
  _leaf_pm_ports_dir="\$SDCARD_PATH/Roms/PORTS"
else
  _leaf_pm_roms_dir=""
  _leaf_pm_ports_dir="/\${directory:-roms}/ports"
fi
if [ -n "\$_leaf_pm_roms_dir" ] &&
   ! awk '\$2 == "/roms/ports" { found = 1 } END { exit found ? 0 : 1 }' /proc/mounts 2>/dev/null; then
  export directory="\${_leaf_pm_roms_dir#/}"
fi
export HM_PORTS_DIR="\${HM_PORTS_DIR:-\$_leaf_pm_ports_dir}"
export HM_SCRIPTS_DIR="\${HM_SCRIPTS_DIR:-\$HM_PORTS_DIR}"

leaf_pm_bind_target_parent() {
  _leaf_pm_bind_target="\${1%/}"
  [ -n "\$_leaf_pm_bind_target" ] || return 0
  _leaf_pm_bind_parent="\$(dirname "\$_leaf_pm_bind_target" 2>/dev/null || printf '.')"
  case "\$_leaf_pm_bind_parent" in
    ""|.) return 0 ;;
  esac
  mkdir -p "\$_leaf_pm_bind_parent" 2>/dev/null || true
}

bind_directories() {
  [ "\$#" -ge 2 ] || return 2
  _leaf_pm_bind_target="\${1%/}"
  [ -n "\$_leaf_pm_bind_target" ] || _leaf_pm_bind_target="\$1"
  leaf_pm_bind_target_parent "\$_leaf_pm_bind_target"
  if [ "\${PM_CAN_MOUNT:-Y}" = "Y" ]; then
    [ -L "\$_leaf_pm_bind_target" ] && rm -f "\$_leaf_pm_bind_target" && echo "removed previous symlink \$_leaf_pm_bind_target"
    if [ -d "\$2" ]; then
      mkdir -p "\$_leaf_pm_bind_target"
      \$ESUDO umount "\$_leaf_pm_bind_target"
      \$ESUDO mount --bind "\$2" "\$_leaf_pm_bind_target" && echo "successful bind mount from \$2 to \$_leaf_pm_bind_target"
    else
      echo "no directory found at \$2"
    fi
  else
    rm -f "\$_leaf_pm_bind_target"
    ln -sfv "\$2" "\$_leaf_pm_bind_target"
  fi
}

bind_files() {
  [ "\$#" -ge 2 ] || return 2
  _leaf_pm_bind_target="\${1%/}"
  [ -n "\$_leaf_pm_bind_target" ] || _leaf_pm_bind_target="\$1"
  leaf_pm_bind_target_parent "\$_leaf_pm_bind_target"
  if [ "\${PM_CAN_MOUNT:-Y}" = "Y" ]; then
    [ -L "\$_leaf_pm_bind_target" ] && rm -f "\$_leaf_pm_bind_target" && echo "removed previous symlink \$_leaf_pm_bind_target"
    if [ -f "\$2" ]; then
      touch "\$_leaf_pm_bind_target"
      \$ESUDO umount "\$_leaf_pm_bind_target"
      \$ESUDO mount --bind "\$2" "\$_leaf_pm_bind_target" && echo "successful bind mount from \$2 to \$_leaf_pm_bind_target"
    else
      echo "no file found at \$2"
    fi
  else
    rm -f "\$_leaf_pm_bind_target"
    ln -sfv "\$2" "\$_leaf_pm_bind_target"
  fi
}

_leaf_pm_system_dir="\${UMRK_PLATFORM_PATH:-}"
if [ -z "\$_leaf_pm_system_dir" ] && [ -n "\${SDCARD_PATH:-}" ]; then
  _leaf_pm_system_dir="\${SDCARD_PATH%/}/.system/leaf/platforms/\${PLATFORM:-mlp1}"
fi
_leaf_pm_internal_dir=""
if [ -n "\${SDCARD_PATH:-}" ]; then
  _leaf_pm_internal_dir="\${SDCARD_PATH%/}/.umrk/\${PLATFORM:-mlp1}"
fi
export LEAF_PM_RETROARCH_BIN="\${LEAF_PM_RETROARCH_BIN:-\${UMRK_RETROARCH_BIN:-\${JAWAKA_RETROARCH_BIN:-}}}"
if [ -z "\$LEAF_PM_RETROARCH_BIN" ] && [ -x "\$_leaf_pm_system_dir/bin/retroarch" ]; then
  export LEAF_PM_RETROARCH_BIN="\$_leaf_pm_system_dir/bin/retroarch"
fi
export LEAF_PM_RETROARCH_CONFIG="\${LEAF_PM_RETROARCH_CONFIG:-\${UMRK_RETROARCH_CONFIG:-\${JAWAKA_RETROARCH_CONFIG:-}}}"
if [ -z "\$LEAF_PM_RETROARCH_CONFIG" ] && [ -f "\$_leaf_pm_internal_dir/retroarch/retroarch.cfg" ]; then
  export LEAF_PM_RETROARCH_CONFIG="\$_leaf_pm_internal_dir/retroarch/retroarch.cfg"
elif [ -z "\$LEAF_PM_RETROARCH_CONFIG" ] && [ -f "\$_leaf_pm_system_dir/defaults/retroarch.cfg" ]; then
  export LEAF_PM_RETROARCH_CONFIG="\$_leaf_pm_system_dir/defaults/retroarch.cfg"
fi
leaf_pm_run_retroarch() {
  _leaf_pm_ra_bin="\${LEAF_PM_RETROARCH_BIN:-}"
  if [ -z "\$_leaf_pm_ra_bin" ]; then
    _leaf_pm_ra_bin="\$(command -v retroarch 2>/dev/null || true)"
  fi
  if [ -z "\$_leaf_pm_ra_bin" ] || [ ! -x "\$_leaf_pm_ra_bin" ]; then
    echo "Leaf PortMaster: RetroArch binary missing" >&2
    return 127
  fi
  if [ -n "\${LEAF_PM_RETROARCH_CONFIG:-}" ] && [ -f "\$LEAF_PM_RETROARCH_CONFIG" ]; then
    "\$_leaf_pm_ra_bin" --config "\$LEAF_PM_RETROARCH_CONFIG" "\$@"
  else
    "\$_leaf_pm_ra_bin" "\$@"
  fi
}

export LEAF_PM_TOOLS_DIR="\${LEAF_PM_TOOLS_DIR:-\$LEAF_PM_DATA_DIR/compat/tools/aarch64/bin}"
if [ -d "\$LEAF_PM_TOOLS_DIR" ]; then
  case ":\${PATH:-}:" in
    *:"\$LEAF_PM_TOOLS_DIR":*) ;;
    *) export PATH="\$LEAF_PM_TOOLS_DIR:\${PATH:-/usr/bin:/usr/sbin:/bin:/sbin}" ;;
  esac
fi

export LEAF_PM_AARCH64_COMPAT_LIB_DIR="\${LEAF_PM_AARCH64_COMPAT_LIB_DIR:-\$LEAF_PM_DATA_DIR/compat/libs/aarch64}"
export LEAF_PM_NATIVE_COMPAT_LIB_DIR="\${LEAF_PM_NATIVE_COMPAT_LIB_DIR:-\$LEAF_PM_AARCH64_COMPAT_LIB_DIR}"
leaf_pm_enable_aarch64_compat_libs() {
  [ "\${DEVICE_ARCH:-aarch64}" = "aarch64" ] || return 0
  [ -d "\${LEAF_PM_AARCH64_COMPAT_LIB_DIR:-}" ] || return 0
  case ":\${LD_LIBRARY_PATH:-}:" in
    *:"\$LEAF_PM_AARCH64_COMPAT_LIB_DIR":*) ;;
    *) export LD_LIBRARY_PATH="\$LEAF_PM_AARCH64_COMPAT_LIB_DIR\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}" ;;
  esac
}
case "\${LEAF_PM_ENABLE_AARCH64_COMPAT_LIBS:-0}" in
  1|true|yes|TRUE|YES) leaf_pm_enable_aarch64_compat_libs ;;
esac

leaf_pm_dir_has_font() {
  [ -d "\${1:-}" ] || return 1
  for _leaf_pm_font in "\$1"/*.ttf "\$1"/*.otf "\$1"/*.ttc; do
    [ -f "\$_leaf_pm_font" ] && unset _leaf_pm_font && return 0
  done
  unset _leaf_pm_font
  return 1
}

leaf_pm_enable_java8_weston_runtime() {
  [ "\${LEAF_PM_JAVA8_WESTON_COMPAT:-1}" != "0" ] || return 0

  case "\${LEAF_PM_JAVA8_WESTON_CLEAR_SDL_VIDEODRIVER:-1}" in
    0|false|no|FALSE|NO) ;;
    *) export SDL_VIDEODRIVER="\${LEAF_PM_JAVA8_WESTON_SDL_VIDEODRIVER:-}" ;;
  esac

  _leaf_pm_java_font_dir="\${LEAF_PM_JAVA8_FONT_DIR:-}"
  if [ -z "\$_leaf_pm_java_font_dir" ]; then
    for _leaf_pm_java_font_candidate in \
      "\${PORTMASTER_CONTROLFOLDER:-}/resources" \
      "\${PORTMASTER_CONTROLFOLDER:-}/pylibs/resources" \
      "\${LEAF_PM_DATA_DIR:-}/PortMaster/resources" \
      "\${LEAF_PM_DATA_DIR:-}/PortMaster/pylibs/resources" \
      "\${CAT_FONTS_DIR:-}" \
      "\${UMRK_LAUNCHER_PATH:-}/res"; do
      if leaf_pm_dir_has_font "\$_leaf_pm_java_font_candidate"; then
        _leaf_pm_java_font_dir="\$_leaf_pm_java_font_candidate"
        break
      fi
    done
  fi

  if [ -n "\$_leaf_pm_java_font_dir" ] && [ -d "\$_leaf_pm_java_font_dir" ]; then
    case " \${JAVA_TOOL_OPTIONS:-} " in
      *" -Dsun.java2d.fontpath="*) ;;
      *) export JAVA_TOOL_OPTIONS="-Dsun.java2d.fontpath=\$_leaf_pm_java_font_dir\${JAVA_TOOL_OPTIONS:+ \$JAVA_TOOL_OPTIONS}" ;;
    esac
  fi

  if [ -z "\${CRUSTY_RESOLUTION:-}" ]; then
    export CRUSTY_RESOLUTION="\${LEAF_PM_JAVA8_WESTON_CRUSTY_RESOLUTION:-\${DISPLAY_WIDTH:-960}x\${DISPLAY_HEIGHT:-720}}"
  fi

  if declare -f leaf_pm_enable_java8_weston_direct_drm >/dev/null 2>&1; then
    leaf_pm_enable_java8_weston_direct_drm || true
  fi

  unset _leaf_pm_java_font_candidate _leaf_pm_java_font_dir
}

export LEAF_PM_EGL_SHIM_DIR="\${LEAF_PM_EGL_SHIM_DIR:-\$LEAF_PM_DATA_DIR/compat/egl/aarch64}"
export LEAF_PM_MALI_AARCH64_DIR="\${LEAF_PM_MALI_AARCH64_DIR:-\$LEAF_PM_DATA_DIR/compat/mali/aarch64}"
leaf_pm_prepare_godot_runtime_env() {
  [ "\${DEVICE_ARCH:-aarch64}" = "aarch64" ] || return 0
  export LEAF_PM_SKIP_WESTONPACK_CLEANUP="\${LEAF_PM_SKIP_WESTONPACK_CLEANUP:-1}"
  # The stock Mali blob mis-tracks in-flight GPU jobs against Godot 4's
  # streamed canvas buffers: the kernel logs "Unhandled Page fault" / job
  # TERMINATED every frame and the screen stays black after the boot splash.
  # The Leaf EGL shim serializes draws to work around it (1 = glFinish after
  # each draw). Override with LEAF_PM_GODOT_DRAW_FINISH=0 to disable.
  export LEAF_EGL_DRAW_FINISH="\${LEAF_PM_GODOT_DRAW_FINISH:-\${LEAF_EGL_DRAW_FINISH:-1}}"
  _leaf_pm_godot_cmd="\${1:-}"
  _leaf_pm_godot_use_mali_default=0
  _leaf_pm_godot_use_mali="\${LEAF_PM_GODOT_USE_MALI_COMPAT:-\$_leaf_pm_godot_use_mali_default}"
  _leaf_pm_wayland_runtime="\${LEAF_PM_WAYLAND_RUNTIME_DIR:-\${XDG_RUNTIME_DIR:-/var/run}}"
  _leaf_pm_wayland_display="\${LEAF_PM_WAYLAND_DISPLAY:-\${WAYLAND_DISPLAY:-wayland-0}}"
  _leaf_pm_egl_shim="\${LEAF_PM_EGL_SHIM_DIR:-}/libEGL.so.1"
  case "\$_leaf_pm_godot_use_mali" in
    1|true|yes|TRUE|YES)
      if [ -f "\${LEAF_PM_MALI_AARCH64_DIR:-}/libmali.so.1" ]; then
        export LEAF_PM_MALI_LIB="\$LEAF_PM_MALI_AARCH64_DIR/libmali.so.1"
        case ":\${LD_LIBRARY_PATH:-}:" in
          *:"\$LEAF_PM_MALI_AARCH64_DIR":*) ;;
          *) export LD_LIBRARY_PATH="\$LEAF_PM_MALI_AARCH64_DIR\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}" ;;
        esac
      fi
      ;;
  esac
  if [ -f "\$_leaf_pm_egl_shim" ]; then
    case ":\${LD_LIBRARY_PATH:-}:" in
      *:"\$LEAF_PM_EGL_SHIM_DIR":*) ;;
      *) export LD_LIBRARY_PATH="\$LEAF_PM_EGL_SHIM_DIR\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}" ;;
    esac
  fi
  export XDG_RUNTIME_DIR="\$_leaf_pm_wayland_runtime"
  export WAYLAND_DISPLAY="\$_leaf_pm_wayland_display"
  export SDL_VIDEODRIVER=wayland
}

leaf_pm_args_have_display_driver() {
  while [ "\$#" -gt 0 ]; do
    case "\$1" in
      --display-driver|--display-driver=*) return 0 ;;
    esac
    shift
  done
  return 1
}

leaf_pm_args_have_window_mode() {
  while [ "\$#" -gt 0 ]; do
    case "\$1" in
      -f|--fullscreen|--fullscreen=*|-w|--windowed|--windowed=*|--resolution|--resolution=*|--position|--position=*) return 0 ;;
    esac
    shift
  done
  return 1
}

leaf_pm_run_godot_wayland_runtime() {
  [ "\$#" -gt 0 ] || return 127
  _leaf_pm_godot_cmd="\$1"
  shift
  leaf_pm_prepare_godot_runtime_env "\$_leaf_pm_godot_cmd"
  if leaf_pm_args_have_display_driver "\$@"; then
    "\$_leaf_pm_godot_cmd" "\$@"
    return \$?
  fi
  "\$_leaf_pm_godot_cmd" --display-driver wayland "\$@"
}

leaf_pm_run_godot_sdl2_runtime() {
  [ "\$#" -gt 0 ] || return 127
  _leaf_pm_godot_cmd="\$1"
  shift
  leaf_pm_prepare_godot_runtime_env "\$_leaf_pm_godot_cmd"
  _leaf_pm_direct_resolution="\${LEAF_PM_GODOT_DIRECT_RESOLUTION:-960x720}"
  if [ -n "\$_leaf_pm_direct_resolution" ] && ! leaf_pm_args_have_window_mode "\$@"; then
    "\$_leaf_pm_godot_cmd" --resolution "\$_leaf_pm_direct_resolution" "\$@"
    return \$?
  fi
  "\$_leaf_pm_godot_cmd" "\$@"
}

leaf_pm_enable_godot_wayland_runtime() {
  _leaf_pm_env_bin="\$(command -v env 2>/dev/null || printf '%s\n' /usr/bin/env)"
  env() {
    if [ "\${1##*/}" = "westonwrap.sh" ] && [ "\${2:-}" != "cleanup" ] && [ "\$#" -ge 6 ]; then
      # MLP1 already has Leaf's Weston running; PortMaster's nested Westonpack
      # wrapper cannot provide the EGL display Godot 4 expects on stock firmware.
      shift
      shift 4
      while [ "\$#" -gt 0 ]; do
        case "\$1" in
          *=*) export "\$1"; shift ;;
          *) break ;;
        esac
      done
      [ "\$#" -gt 0 ] || return 127
      _leaf_pm_godot_cmd="\$1"
      shift
      leaf_pm_run_godot_wayland_runtime "\$_leaf_pm_godot_cmd" "\$@"
      return \$?
    fi
    "\$_leaf_pm_env_bin" "\$@"
  }
  if command -v sudo >/dev/null 2>&1; then
    sudo() {
      if [ "\${1:-}" = "env" ] && [ "\${2##*/}" = "westonwrap.sh" ]; then
        shift
        env "\$@"
        return \$?
      fi
      if [ "\${2:-}" = "env" ] && [ "\${3##*/}" = "westonwrap.sh" ]; then
        shift 2
        env "\$@"
        return \$?
      fi
      if [ "\${3:-}" = "env" ] && [ "\${4##*/}" = "westonwrap.sh" ]; then
        shift 3
        env "\$@"
        return \$?
      fi
      command sudo "\$@"
    }
  fi
}

leaf_pm_enable_egl_gles_shim() {
  leaf_pm_enable_godot_wayland_runtime "\$@"
}

export LEAF_PM_RUNTIME_DIR="\${LEAF_PM_RUNTIME_DIR:-\$LEAF_PM_DATA_DIR/runtime}"
if [ -x "\$LEAF_PM_RUNTIME_DIR/bin/python3" ]; then
  _leaf_pm_python_shim_dir="/tmp/leaf-portmaster-python"
  if mkdir -p "\$_leaf_pm_python_shim_dir" 2>/dev/null; then
    cat >"\$_leaf_pm_python_shim_dir/python3" <<'LEAF_PM_PYTHON_SHIM'
#!/bin/sh
_runtime="\${LEAF_PM_RUNTIME_DIR:-}"
if [ -z "\$_runtime" ] || [ ! -x "\$_runtime/bin/python3" ]; then
  echo "Leaf PortMaster python runtime missing" >&2
  exit 127
fi
if [ -n "\${LD_LIBRARY_PATH:-}" ]; then
  export LD_LIBRARY_PATH="\$_runtime/lib:\$LD_LIBRARY_PATH"
else
  export LD_LIBRARY_PATH="\$_runtime/lib"
fi
export PYTHONHOME="\$_runtime"
export PYTHONPATH="\$_runtime/lib/python3.10:\$_runtime/lib/python3.10/site-packages:\$_runtime/lib\${PYTHONPATH:+:\$PYTHONPATH}"
export PYTHONDONTWRITEBYTECODE="\${PYTHONDONTWRITEBYTECODE:-1}"
exec "\$_runtime/bin/python3" "\$@"
LEAF_PM_PYTHON_SHIM
    chmod 755 "\$_leaf_pm_python_shim_dir/python3" 2>/dev/null || true
    cp -f "\$_leaf_pm_python_shim_dir/python3" "\$_leaf_pm_python_shim_dir/python" 2>/dev/null || true
    case ":\${PATH:-}:" in
      *:"\$_leaf_pm_python_shim_dir":*) ;;
      *) export PATH="\$_leaf_pm_python_shim_dir:\${PATH:-/usr/bin:/usr/sbin}" ;;
    esac
  fi
fi

leaf_pm_apply_controller_layout() {
  if [ "\${PORTMASTER_LEAF_PORT_LAYOUT_SCOPE:-ports}" = "gui" ]; then
    export PORTMASTER_LEAF_CONTROLLER_LAYOUT="gui"
    export SDL_GAMECONTROLLERCONFIG='$controller_gui'
  elif [ -f "\$LEAF_PM_DATA_DIR/x360" ]; then
    export PORTMASTER_LEAF_CONTROLLER_LAYOUT="x360"
    export SDL_GAMECONTROLLERCONFIG='$controller_x360'
  elif [ -f "\$LEAF_PM_DATA_DIR/nintendo" ]; then
    export PORTMASTER_LEAF_CONTROLLER_LAYOUT="nintendo"
    export SDL_GAMECONTROLLERCONFIG='$controller_nintendo'
  else
    export PORTMASTER_LEAF_CONTROLLER_LAYOUT="nintendo"
    export SDL_GAMECONTROLLERCONFIG='$controller_nintendo'
  fi
  export sdl_controllerconfig="\$SDL_GAMECONTROLLERCONFIG"
  export SDL_GAMECONTROLLERCONFIG_FILE="/tmp/leaf-portmaster-gamecontrollerdb.txt"
  printf '%s\n' "\$SDL_GAMECONTROLLERCONFIG" >"\$SDL_GAMECONTROLLERCONFIG_FILE" 2>/dev/null || true
}

leaf_pm_resolve_cfw_version() {
  _leaf_pm_release_version=""
  for _leaf_pm_release_file in \
    "\${SDCARD_PATH:-}/.system/leaf/platforms/\${PLATFORM:-mlp1}/release.json" \
    "\${SDCARD_PATH:-}/.system/leaf/platforms/\${PLATFORM:-mlp1}/manifest.json" \
    "\${SDCARD_PATH:-}/.umrk/\${PLATFORM:-mlp1}/release.json"; do
    [ -f "\$_leaf_pm_release_file" ] || continue
    _leaf_pm_release_version="\$(sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p; s/.*"release_id"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "\$_leaf_pm_release_file" 2>/dev/null | head -n 1)"
    [ -n "\$_leaf_pm_release_version" ] && break
  done
  [ -n "\$_leaf_pm_release_version" ] || _leaf_pm_release_version="portmaster-mlp1"
  printf '%s\n' "\$_leaf_pm_release_version"
}

if [ -z "\${CFW_VERSION:-}" ] || [ "\$CFW_VERSION" = "Unknown" ]; then
  export CFW_VERSION="\$(leaf_pm_resolve_cfw_version)"
fi
export CFW_NAME="\${CFW_NAME:-Leaf}"

if [ -f /tmp/leaf-pm-mount-probe-failed ]; then
  export PM_CAN_MOUNT=N
else
  export PM_CAN_MOUNT="\${PM_CAN_MOUNT:-Y}"
fi

if command -v taskset >/dev/null 2>&1 && taskset 0xF true >/dev/null 2>&1; then
  export TASKSET="\${TASKSET:-taskset 0xF}"
else
  export TASKSET=""
fi

leaf_pm_json_escape() {
  printf '%s' "\${1:-}" | sed 's/\\\\/\\\\\\\\/g; s/"/\\\\"/g'
}

leaf_pm_env_source_for() {
  case "\$1" in
    PLATFORM|SDCARD_PATH|USERDATA_PATH|LOGS_PATH|ROMS_PATH|IMAGES_PATH|UMRK_*|JAWAKA_*)
      printf '%s\n' leaf-session-env ;;
    ESUDO|ESUDOKILL|ESUDOKILL2|GPTOKEYB|GPTOKEYB2|directory|PM_CAN_MOUNT|TASKSET)
      printf '%s\n' upstream-control ;;
    LEAF_PM_*|PATH|LD_LIBRARY_PATH|LD_PRELOAD|PYTHONHOME|PYTHONPATH|PYTHONDONTWRITEBYTECODE|SDL_GAMECONTROLLERCONFIG_FILE)
      printf '%s\n' shim ;;
    *)
      printf '%s\n' leaf-hook ;;
  esac
}

leaf_pm_snapshot_value() {
  _leaf_pm_snapshot_name="\$1"
  eval "printf '%s' \"\\\${\${_leaf_pm_snapshot_name}:-}\""
}

leaf_pm_write_snapshot_pair() {
  _leaf_pm_snapshot_mode="\$1"
  _leaf_pm_snapshot_base="\$2"
  _leaf_pm_snapshot_dir="\${LEAF_PM_DATA_DIR:-\${XDG_DATA_HOME:-}}/.leaf"
  [ -n "\$_leaf_pm_snapshot_dir" ] || return 1
  mkdir -p "\$_leaf_pm_snapshot_dir" 2>/dev/null || return 1

  _leaf_pm_snapshot_json="\$_leaf_pm_snapshot_dir/\$_leaf_pm_snapshot_base.json"
  _leaf_pm_snapshot_txt="\$_leaf_pm_snapshot_dir/\$_leaf_pm_snapshot_base.txt"
  _leaf_pm_snapshot_json_tmp="\$_leaf_pm_snapshot_json.tmp.\$\$"
  _leaf_pm_snapshot_txt_tmp="\$_leaf_pm_snapshot_txt.tmp.\$\$"
  _leaf_pm_snapshot_generated_at="\$(date +%s 2>/dev/null || printf '%s' 0)"
  _leaf_pm_snapshot_vars="PLATFORM SDCARD_PATH USERDATA_PATH LOGS_PATH ROMS_PATH IMAGES_PATH HOME XDG_DATA_HOME HM_TOOLS_DIR HM_PORTS_DIR HM_SCRIPTS_DIR PORTMASTER_CONTROLFOLDER CFW_NAME CFW_VERSION DEVICE_NAME DEVICE_CPU DEVICE_ARCH DEVICE_RAM DEVICE_HAS_ARMHF DEVICE_HAS_AARCH64 DEVICE_HAS_X86 DEVICE_HAS_X86_64 DISPLAY_WIDTH DISPLAY_HEIGHT DISPLAY_ORIENTATION ASPECT_X ASPECT_Y ANALOG_STICKS ANALOGSTICKS ESUDO ESUDOKILL ESUDOKILL2 GPTOKEYB GPTOKEYB2 directory PM_CAN_MOUNT TASKSET PORTMASTER_LEAF_PORT_LAYOUT_SCOPE PORTMASTER_LEAF_CONTROLLER_LAYOUT SDL_GAMECONTROLLERCONFIG sdl_controllerconfig SDL_GAMECONTROLLERCONFIG_FILE LEAF_PM_TOOLS_DIR LEAF_PM_RUNTIME_DIR LEAF_PM_ARMHF_ROOT LEAF_PM_ARMHF_RUN LEAF_PM_ARMHF_LOADER LEAF_PM_ARMHF_LIB_PATH LEAF_PM_BOX86 LEAF_PM_RETROARCH_BIN LEAF_PM_RETROARCH_CONFIG LEAF_PM_AARCH64_COMPAT_LIB_DIR LEAF_PM_NATIVE_COMPAT_LIB_DIR LEAF_PM_AARCH64_SDL2_FULLSCREEN_SHIM LEAF_PM_SDL_FORCE_FULLSCREEN LEAF_PM_LAUNCH_MODE"

  {
    printf '{\n'
    printf '  "schema": 1,\n'
    printf '  "kind": "portmaster-launch-env",\n'
    printf '  "mode": "%s",\n' "\$(leaf_pm_json_escape "\$_leaf_pm_snapshot_mode")"
    printf '  "generated_at_unix": %s,\n' "\$_leaf_pm_snapshot_generated_at"
    printf '  "manager_version": "hook",\n'
    printf '  "platform": "%s",\n' "\$(leaf_pm_json_escape "\${PLATFORM:-}")"
    printf '  "sdcard_path": "%s",\n' "\$(leaf_pm_json_escape "\${SDCARD_PATH:-}")"
    printf '  "entries": [\n'
    _leaf_pm_snapshot_first=1
    for _leaf_pm_snapshot_var in \$_leaf_pm_snapshot_vars; do
      _leaf_pm_snapshot_value="\$(leaf_pm_snapshot_value "\$_leaf_pm_snapshot_var")"
      _leaf_pm_snapshot_source="\$(leaf_pm_env_source_for "\$_leaf_pm_snapshot_var")"
      if [ "\$_leaf_pm_snapshot_first" -eq 0 ]; then
        printf ',\n'
      fi
      _leaf_pm_snapshot_first=0
      printf '    {"name":"%s","value":"%s","source":"%s"}' \
        "\$(leaf_pm_json_escape "\$_leaf_pm_snapshot_var")" \
        "\$(leaf_pm_json_escape "\$_leaf_pm_snapshot_value")" \
        "\$(leaf_pm_json_escape "\$_leaf_pm_snapshot_source")"
    done
    printf '\n  ]\n'
    printf '}\n'
  } >"\$_leaf_pm_snapshot_json_tmp" || return 1

  {
    printf 'schema=1\n'
    printf 'kind=portmaster-launch-env\n'
    printf 'mode=%s\n' "\$_leaf_pm_snapshot_mode"
    printf 'generated_at_unix=%s\n' "\$_leaf_pm_snapshot_generated_at"
    printf 'manager_version=hook\n'
    printf 'platform=%s\n' "\${PLATFORM:-}"
    printf 'sdcard_path=%s\n' "\${SDCARD_PATH:-}"
    printf '\n# name\tsource\tvalue\n'
    for _leaf_pm_snapshot_var in \$_leaf_pm_snapshot_vars; do
      _leaf_pm_snapshot_value="\$(leaf_pm_snapshot_value "\$_leaf_pm_snapshot_var")"
      _leaf_pm_snapshot_source="\$(leaf_pm_env_source_for "\$_leaf_pm_snapshot_var")"
      printf '%s\t%s\t%s\n' "\$_leaf_pm_snapshot_var" "\$_leaf_pm_snapshot_source" "\$_leaf_pm_snapshot_value"
    done
  } >"\$_leaf_pm_snapshot_txt_tmp" || return 1

  [ -f "\$_leaf_pm_snapshot_json" ] && mv -f "\$_leaf_pm_snapshot_json" "\$_leaf_pm_snapshot_dir/\$_leaf_pm_snapshot_base.previous.json" 2>/dev/null || true
  [ -f "\$_leaf_pm_snapshot_txt" ] && mv -f "\$_leaf_pm_snapshot_txt" "\$_leaf_pm_snapshot_dir/\$_leaf_pm_snapshot_base.previous.txt" 2>/dev/null || true
  mv -f "\$_leaf_pm_snapshot_json_tmp" "\$_leaf_pm_snapshot_json" || return 1
  mv -f "\$_leaf_pm_snapshot_txt_tmp" "\$_leaf_pm_snapshot_txt" || return 1
}

leaf_pm_write_launch_env_snapshot() {
  _leaf_pm_snapshot_mode="\${1:-\${LEAF_PM_LAUNCH_MODE:-port}}"
  case "\$_leaf_pm_snapshot_mode" in
    latest|"") _leaf_pm_snapshot_mode="port" ;;
  esac
  _leaf_pm_snapshot_slug="\$(printf '%s' "\$_leaf_pm_snapshot_mode" | sed 's/[^A-Za-z0-9_-]/_/g')"
  [ -n "\$_leaf_pm_snapshot_slug" ] || _leaf_pm_snapshot_slug="port"
  _leaf_pm_snapshot_force=0
  case "\${LEAF_PM_ENV_PROBE:-0}" in
    1|true|yes|TRUE|YES) _leaf_pm_snapshot_force=1 ;;
  esac
  _leaf_pm_snapshot_marker="/tmp/leaf-pm-env-snapshot-\$_leaf_pm_snapshot_slug"
  if [ "\$_leaf_pm_snapshot_force" -ne 1 ] && [ -f "\$_leaf_pm_snapshot_marker" ]; then
    return 0
  fi
  leaf_pm_write_snapshot_pair "\$_leaf_pm_snapshot_mode" "launch-env-\$_leaf_pm_snapshot_slug" || return 1
  if [ "\$_leaf_pm_snapshot_force" -eq 1 ]; then
    leaf_pm_write_snapshot_pair "\$_leaf_pm_snapshot_mode" "launch-env" || return 1
  fi
  touch "\$_leaf_pm_snapshot_marker" 2>/dev/null || true
}

if declare -f get_controls >/dev/null 2>&1; then
  if ! declare -f leaf_pm_upstream_get_controls >/dev/null 2>&1; then
    eval "\$(declare -f get_controls | sed '1s/get_controls/leaf_pm_upstream_get_controls/')"
  fi
  get_controls() {
    leaf_pm_upstream_get_controls "\$@"
    leaf_pm_apply_controller_layout
    _leaf_pm_snapshot_mode="\${LEAF_PM_ENV_PROBE_MODE:-\${LEAF_PM_LAUNCH_MODE:-port}}"
    leaf_pm_write_launch_env_snapshot "\$_leaf_pm_snapshot_mode" || true
    case "\${LEAF_PM_ENV_PROBE:-0}" in
      1|true|yes|TRUE|YES)
        echo "Leaf PortMaster env probe wrote launch-env-\$_leaf_pm_snapshot_mode under \${LEAF_PM_DATA_DIR:-\${XDG_DATA_HOME:-}}/.leaf" >&2
        exit 0
        ;;
    esac
  }
fi

leaf_pm_apply_controller_layout

export DEVICE_HAS_ARMHF="\${DEVICE_HAS_ARMHF:-N}"
export DEVICE_HAS_AARCH64="\${DEVICE_HAS_AARCH64:-Y}"

export LEAF_PM_AARCH64_DRM_ROTATE_SHIM="\${LEAF_PM_AARCH64_DRM_ROTATE_SHIM:-\$LEAF_PM_DATA_DIR/compat/drm/aarch64/leaf-drm-rotate.so}"

leaf_pm_prepend_ld_preload() {
  _leaf_pm_preload_path="\${1:-}"
  [ -n "\$_leaf_pm_preload_path" ] && [ -f "\$_leaf_pm_preload_path" ] || return 1
  case ":\${LD_PRELOAD:-}:" in
    *:"\$_leaf_pm_preload_path":*) ;;
    *) export LD_PRELOAD="\$_leaf_pm_preload_path\${LD_PRELOAD:+:\$LD_PRELOAD}" ;;
  esac
}

leaf_pm_prepend_ld_library_path() {
  _leaf_pm_lib_path="\${1:-}"
  [ -n "\$_leaf_pm_lib_path" ] && [ -d "\$_leaf_pm_lib_path" ] || return 1
  case ":\${LD_LIBRARY_PATH:-}:" in
    *:"\$_leaf_pm_lib_path":*) ;;
    *) export LD_LIBRARY_PATH="\$_leaf_pm_lib_path\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}" ;;
  esac
}

leaf_pm_pidof() {
  command -v pidof >/dev/null 2>&1 || return 1
  pidof "\$1" >/dev/null 2>&1
}

leaf_pm_prepend_wrapped_preload() {
  _leaf_pm_wrapped_preload_path="\${1:-}"
  [ -n "\$_leaf_pm_wrapped_preload_path" ] && [ -f "\$_leaf_pm_wrapped_preload_path" ] || return 1
  case ":\${WRAPPED_PRELOAD:-}:" in
    *:"\$_leaf_pm_wrapped_preload_path":*) ;;
    *) export WRAPPED_PRELOAD="\$_leaf_pm_wrapped_preload_path\${WRAPPED_PRELOAD:+:\$WRAPPED_PRELOAD}" ;;
  esac
}

leaf_pm_restore_java8_weston_direct_drm() {
  [ "\${LEAF_PM_JAVA8_WESTON_DIRECT_DRM_STACK_STOPPED:-0}" = "1" ] || return 0
  export LEAF_PM_JAVA8_WESTON_DIRECT_DRM_STACK_STOPPED=0
  trap - EXIT HUP INT TERM
  if [ "\${LEAF_PM_JAVA8_WESTON_DIRECT_DRM_WESTON_WAS_RUNNING:-0}" = "1" ] &&
     [ -x /etc/init.d/S49weston ]; then
    /etc/init.d/S49weston start < /dev/null > /dev/null 2>&1 || true
    sleep "\${LEAF_PM_JAVA8_WESTON_START_DELAY:-1}"
  fi
}

leaf_pm_begin_java8_weston_direct_drm() {
  [ "\${LEAF_PM_JAVA8_WESTON_DIRECT_DRM_ACTIVE:-0}" = "1" ] || return 0
  [ "\${LEAF_PM_JAVA8_WESTON_DIRECT_DRM_BEGUN:-0}" != "1" ] || return 0
  export LEAF_PM_JAVA8_WESTON_DIRECT_DRM_BEGUN=1

  _leaf_pm_java8_stop_display="\${LEAF_PM_JAVA8_WESTON_STOP_DISPLAY:-}"
  if [ -z "\$_leaf_pm_java8_stop_display" ]; then
    case "\${JAWAKA_DIRECT_DRM:-0}" in
      1|true|yes|TRUE|YES) _leaf_pm_java8_stop_display=0 ;;
      *) _leaf_pm_java8_stop_display=1 ;;
    esac
  fi
  case "\$_leaf_pm_java8_stop_display" in
    0|false|no|FALSE|NO) return 0 ;;
  esac

  export LEAF_PM_JAVA8_WESTON_DIRECT_DRM_WESTON_WAS_RUNNING=0
  if leaf_pm_pidof weston; then
    export LEAF_PM_JAVA8_WESTON_DIRECT_DRM_WESTON_WAS_RUNNING=1
  fi

  trap 'leaf_pm_restore_java8_weston_direct_drm' EXIT HUP INT TERM
  if [ -x /etc/init.d/S49weston ]; then
    /etc/init.d/S49weston stop < /dev/null > /dev/null 2>&1 || true
  fi
  sleep "\${LEAF_PM_JAVA8_WESTON_STOP_DELAY:-1}"
  export LEAF_PM_JAVA8_WESTON_DIRECT_DRM_STACK_STOPPED=1
}

leaf_pm_enable_java8_weston_direct_drm() {
  [ "\${DEVICE_ARCH:-aarch64}" = "aarch64" ] || return 0
  case "\${LEAF_PM_JAVA8_WESTON_DIRECT_DRM:-1}" in
    0|false|no|FALSE|NO) return 0 ;;
  esac
  [ -f "\$LEAF_PM_AARCH64_DRM_ROTATE_SHIM" ] || return 0

  export LEAF_DRM_ROTATE="\${LEAF_DRM_ROTATE:-270}"
  export SDL_VIDEODRIVER="\${LEAF_PM_JAVA8_WESTON_SDL_VIDEODRIVER:-kmsdrm}"
  leaf_pm_prepend_wrapped_preload "\$LEAF_PM_AARCH64_DRM_ROTATE_SHIM" || return 0
  export LEAF_PM_JAVA8_WESTON_DIRECT_DRM_ACTIVE=1
  leaf_pm_begin_java8_weston_direct_drm
}

leaf_pm_enable_gothic_machismo_vulkan_rotate() {
  [ "\${DEVICE_ARCH:-aarch64}" = "aarch64" ] || return 1
  case "\${LEAF_PM_GOTHIC_MACHISMO_VULKAN_ROTATE:-\${JAWAKA_DIRECT_DRM:-0}}" in
    1|true|yes|TRUE|YES) ;;
    *) return 1 ;;
  esac
  case "\${GOTHIC_BACKEND:-}" in
    ""|vulkan) ;;
    *) return 1 ;;
  esac
  [ -f "\$LEAF_PM_AARCH64_DRM_ROTATE_SHIM" ] || return 1

  _leaf_pm_vk_dir="\${LEAF_PM_VULKAN_STACK_DIR:-}"
  if [ -z "\$_leaf_pm_vk_dir" ] &&
     [ -f "\${LEAF_PM_MALI_AARCH64_DIR:-}/libmali.so.1" ] &&
     { [ -f "\${LEAF_PM_MALI_AARCH64_DIR:-}/rk_vk_g29.json" ] ||
       [ -f "\${LEAF_PM_MALI_AARCH64_DIR:-}/rk_vk.json" ] ||
       [ -f "\${LEAF_PM_MALI_AARCH64_DIR:-}/rk_vk_g24.json" ]; }; then
    _leaf_pm_vk_dir="\$LEAF_PM_MALI_AARCH64_DIR"
  fi
  _leaf_pm_vk_dir="\${_leaf_pm_vk_dir:-\$LEAF_PM_DATA_DIR/compat/vulkan/aarch64}"
  if [ -d "\$_leaf_pm_vk_dir" ]; then
    leaf_pm_prepend_ld_library_path "\$_leaf_pm_vk_dir" || true
    if [ -z "\${VK_ICD_FILENAMES:-}" ]; then
      if [ -f "\$_leaf_pm_vk_dir/rk_vk_g29.json" ]; then
        export VK_ICD_FILENAMES="\$_leaf_pm_vk_dir/rk_vk_g29.json"
      elif [ -f "\$_leaf_pm_vk_dir/rk_vk.json" ]; then
        export VK_ICD_FILENAMES="\$_leaf_pm_vk_dir/rk_vk.json"
      elif [ -f "\$_leaf_pm_vk_dir/rk_vk_g24.json" ]; then
        export VK_ICD_FILENAMES="\$_leaf_pm_vk_dir/rk_vk_g24.json"
      fi
    fi
  fi
  if [ -z "\${VK_ICD_FILENAMES:-}" ] && [ ! -f /usr/share/vulkan/icd.d/rk_vk.json ]; then
    return 1
  fi

  export GOTHIC_BACKEND=vulkan
  export SDL_VIDEODRIVER=kmsdrm
  export LEAF_DRM_ROTATE="\${LEAF_DRM_ROTATE:-270}"
  case "\${VK_LOADER_LAYERS_DISABLE:-}" in
    *VK_LAYER_window_system_integration*) ;;
    "") export VK_LOADER_LAYERS_DISABLE="VK_LAYER_window_system_integration" ;;
    *) export VK_LOADER_LAYERS_DISABLE="\$VK_LOADER_LAYERS_DISABLE,VK_LAYER_window_system_integration" ;;
  esac
  leaf_pm_prepend_ld_preload "\$LEAF_PM_AARCH64_DRM_ROTATE_SHIM" || return 1
  export LEAF_PM_GOTHIC_MACHISMO_VULKAN_ROTATE_ACTIVE=1
}

leaf_pm_restore_gothic_machismo_vulkan_rotate() {
  [ "\${LEAF_PM_GOTHIC_MACHISMO_VULKAN_ROTATE_STACK_STOPPED:-0}" = "1" ] || return 0
  export LEAF_PM_GOTHIC_MACHISMO_VULKAN_ROTATE_STACK_STOPPED=0
  trap - EXIT HUP INT TERM
  if [ "\${LEAF_PM_GOTHIC_MACHISMO_VULKAN_ROTATE_WESTON_WAS_RUNNING:-0}" = "1" ] &&
     [ -x /etc/init.d/S49weston ]; then
    /etc/init.d/S49weston start < /dev/null > /dev/null 2>&1 || true
    sleep 1
  fi
  if [ "\${LEAF_PM_GOTHIC_MACHISMO_VULKAN_ROTATE_LEAF_WAS_RUNNING:-0}" = "1" ] &&
     [ -x /etc/init.d/S50leaf ]; then
    /etc/init.d/S50leaf start < /dev/null > /dev/null 2>&1 || true
  fi
}

leaf_pm_begin_gothic_machismo_vulkan_rotate() {
  [ "\${LEAF_PM_GOTHIC_MACHISMO_VULKAN_ROTATE_ACTIVE:-0}" = "1" ] || return 0
  [ "\${LEAF_PM_GOTHIC_MACHISMO_VULKAN_ROTATE_BEGUN:-0}" != "1" ] || return 0
  export LEAF_PM_GOTHIC_MACHISMO_VULKAN_ROTATE_BEGUN=1
  _leaf_pm_stop_display="\${LEAF_PM_GOTHIC_MACHISMO_VULKAN_ROTATE_STOP_DISPLAY:-}"
  if [ -z "\$_leaf_pm_stop_display" ]; then
    case "\${JAWAKA_DIRECT_DRM:-0}" in
      1|true|yes|TRUE|YES) _leaf_pm_stop_display=0 ;;
      *) _leaf_pm_stop_display=1 ;;
    esac
  fi
  case "\$_leaf_pm_stop_display" in
    0|false|no|FALSE|NO) return 0 ;;
  esac

  export LEAF_PM_GOTHIC_MACHISMO_VULKAN_ROTATE_WESTON_WAS_RUNNING=0
  export LEAF_PM_GOTHIC_MACHISMO_VULKAN_ROTATE_LEAF_WAS_RUNNING=0
  if leaf_pm_pidof weston; then
    export LEAF_PM_GOTHIC_MACHISMO_VULKAN_ROTATE_WESTON_WAS_RUNNING=1
  fi
  if leaf_pm_pidof jawaka-launcher || leaf_pm_pidof jawaka-osd || leaf_pm_pidof jawaka-ledd; then
    export LEAF_PM_GOTHIC_MACHISMO_VULKAN_ROTATE_LEAF_WAS_RUNNING=1
  fi

  trap 'leaf_pm_restore_gothic_machismo_vulkan_rotate' EXIT HUP INT TERM
  if [ -x /etc/init.d/S50leaf ]; then
    /etc/init.d/S50leaf stop < /dev/null > /dev/null 2>&1 || true
  fi
  if [ -x /etc/init.d/S49weston ]; then
    /etc/init.d/S49weston stop < /dev/null > /dev/null 2>&1 || true
  fi
  sleep "\${LEAF_PM_GOTHIC_MACHISMO_VULKAN_ROTATE_STOP_DELAY:-2}"
  export LEAF_PM_GOTHIC_MACHISMO_VULKAN_ROTATE_STACK_STOPPED=1
}

export LEAF_PM_AARCH64_SDL2_FULLSCREEN_SHIM="\${LEAF_PM_AARCH64_SDL2_FULLSCREEN_SHIM:-\$LEAF_PM_DATA_DIR/compat/sdl2/aarch64/leaf-sdl2-fullscreen.so}"

leaf_pm_enable_sdl2_fullscreen_env() {
  _leaf_pm_sdl2_port="\${1:-}"
  _leaf_pm_sdl2_arches=",\${2:-},"
  [ "\${LEAF_PM_SDL_FORCE_FULLSCREEN:-}" = "0" ] && return 0

  if [ -n "\$_leaf_pm_sdl2_port" ] && [ -f "\$LEAF_PM_DATA_DIR/sdl2-fullscreen-optout.txt" ]; then
    while IFS= read -r _leaf_pm_sdl2_optout; do
      [ "\$_leaf_pm_sdl2_optout" = "\$_leaf_pm_sdl2_port" ] && return 0
    done <"\$LEAF_PM_DATA_DIR/sdl2-fullscreen-optout.txt"
  fi

  export LEAF_PM_SDL_FORCE_FULLSCREEN=1
  export LEAF_PM_SDL_FULLSCREEN_WIDTH="\${LEAF_PM_SDL_FULLSCREEN_WIDTH:-\${DISPLAY_WIDTH:-960}}"
  export LEAF_PM_SDL_FULLSCREEN_HEIGHT="\${LEAF_PM_SDL_FULLSCREEN_HEIGHT:-\${DISPLAY_HEIGHT:-720}}"

  case "\$_leaf_pm_sdl2_arches" in
    *,aarch64,*)
      if [ -f "\$LEAF_PM_AARCH64_SDL2_FULLSCREEN_SHIM" ]; then
        case ":\${LD_PRELOAD:-}:" in
          *:"\$LEAF_PM_AARCH64_SDL2_FULLSCREEN_SHIM":*) ;;
          *) export LD_PRELOAD="\$LEAF_PM_AARCH64_SDL2_FULLSCREEN_SHIM\${LD_PRELOAD:+:\$LD_PRELOAD}" ;;
        esac
      fi
      ;;
  esac

  case "\$_leaf_pm_sdl2_arches" in
    *,armhf,*)
      if [ -n "\${LEAF_PM_ARMHF_SDL2_FULLSCREEN_SHIM:-}" ] && [ -f "\$LEAF_PM_ARMHF_SDL2_FULLSCREEN_SHIM" ]; then
        case ":\${LEAF_PM_ARMHF_PRELOAD:-}:" in
          *:"\$LEAF_PM_ARMHF_SDL2_FULLSCREEN_SHIM":*) ;;
          *) export LEAF_PM_ARMHF_PRELOAD="\$LEAF_PM_ARMHF_SDL2_FULLSCREEN_SHIM\${LEAF_PM_ARMHF_PRELOAD:+:\$LEAF_PM_ARMHF_PRELOAD}" ;;
        esac
      fi
      ;;
  esac
}

leaf_pm_run_aarch64_sdl2_fullscreen() {
  [ "\$#" -gt 0 ] || return 127
  _leaf_pm_aarch64_sdl2_cmd="\$1"
  shift
  if [ ! -f "\$LEAF_PM_AARCH64_SDL2_FULLSCREEN_SHIM" ]; then
    "\$_leaf_pm_aarch64_sdl2_cmd" "\$@"
    return \$?
  fi
  _leaf_pm_aarch64_sdl2_preload="\${LD_PRELOAD:-}"
  case ":\$_leaf_pm_aarch64_sdl2_preload:" in
    *:"\$LEAF_PM_AARCH64_SDL2_FULLSCREEN_SHIM":*) ;;
    *) _leaf_pm_aarch64_sdl2_preload="\$LEAF_PM_AARCH64_SDL2_FULLSCREEN_SHIM\${_leaf_pm_aarch64_sdl2_preload:+:\$_leaf_pm_aarch64_sdl2_preload}" ;;
  esac
  LEAF_PM_SDL_FORCE_FULLSCREEN=1 \
  LEAF_PM_SDL_FULLSCREEN_WIDTH="\${LEAF_PM_SDL_FULLSCREEN_WIDTH:-\${DISPLAY_WIDTH:-960}}" \
  LEAF_PM_SDL_FULLSCREEN_HEIGHT="\${LEAF_PM_SDL_FULLSCREEN_HEIGHT:-\${DISPLAY_HEIGHT:-720}}" \
  LD_PRELOAD="\$_leaf_pm_aarch64_sdl2_preload" \
    "\$_leaf_pm_aarch64_sdl2_cmd" "\$@"
}

export LEAF_PM_ARMHF_ROOT="\${LEAF_PM_ARMHF_ROOT:-\$LEAF_PM_DATA_DIR/compat/armhf}"
if [ -f "\$LEAF_PM_ARMHF_ROOT/lib/ld-linux-armhf.so.3" ] && [ -f "\$LEAF_PM_ARMHF_ROOT/bin/leaf-armhf-run" ]; then
  export DEVICE_HAS_ARMHF="Y"
  export LEAF_PM_ARMHF_LOADER="\$LEAF_PM_ARMHF_ROOT/lib/ld-linux-armhf.so.3"
  export LEAF_PM_ARMHF_RUN="\$LEAF_PM_ARMHF_ROOT/bin/leaf-armhf-run"
  export LEAF_PM_ARMHF_LIB_PATH="\$LEAF_PM_ARMHF_ROOT/usr/lib/arm-linux-gnueabihf/mali:\$LEAF_PM_ARMHF_ROOT/lib/arm-linux-gnueabihf:\$LEAF_PM_ARMHF_ROOT/usr/lib/arm-linux-gnueabihf:\$LEAF_PM_ARMHF_ROOT/usr/lib/arm-linux-gnueabihf/pulseaudio:\$LEAF_PM_ARMHF_ROOT/lib:\$LEAF_PM_ARMHF_ROOT/usr/lib"
  export LEAF_PM_ARMHF_SDL_VIDEO_EGL_DRIVER="\${LEAF_PM_ARMHF_SDL_VIDEO_EGL_DRIVER:-libEGL.so}"
  export LEAF_PM_ARMHF_SDL_VIDEO_GL_DRIVER="\${LEAF_PM_ARMHF_SDL_VIDEO_GL_DRIVER:-libGLESv2.so}"
  export SDL_VIDEO_EGL_DRIVER="\${SDL_VIDEO_EGL_DRIVER:-\$LEAF_PM_ARMHF_SDL_VIDEO_EGL_DRIVER}"
  export SDL_VIDEO_GL_DRIVER="\${SDL_VIDEO_GL_DRIVER:-\$LEAF_PM_ARMHF_SDL_VIDEO_GL_DRIVER}"
  if [ -x "\$LEAF_PM_ARMHF_ROOT/bin/box86" ]; then
    export LEAF_PM_BOX86="\$LEAF_PM_ARMHF_ROOT/bin/box86"
  fi
  export LEAF_PM_ARMHF_SDL2_FULLSCREEN_SHIM="\${LEAF_PM_ARMHF_SDL2_FULLSCREEN_SHIM:-\$LEAF_PM_ARMHF_ROOT/bin/leaf-sdl2-fullscreen.so}"

  leaf_pm_armhf_run() {
    "\$LEAF_PM_ARMHF_RUN" "\$@"
  }

  leaf_pm_run_armhf_sdl2_fullscreen() {
    [ "\$#" -gt 0 ] || return 127
    _leaf_pm_armhf_sdl2_cmd="\$1"
    shift
    if [ ! -f "\$LEAF_PM_ARMHF_SDL2_FULLSCREEN_SHIM" ]; then
      "\$_leaf_pm_armhf_sdl2_cmd" "\$@"
      return \$?
    fi
    _leaf_pm_armhf_sdl2_preload="\${LEAF_PM_ARMHF_PRELOAD:-}"
    case ":\$_leaf_pm_armhf_sdl2_preload:" in
      *:"\$LEAF_PM_ARMHF_SDL2_FULLSCREEN_SHIM":*) ;;
      *) _leaf_pm_armhf_sdl2_preload="\$LEAF_PM_ARMHF_SDL2_FULLSCREEN_SHIM\${_leaf_pm_armhf_sdl2_preload:+:\$_leaf_pm_armhf_sdl2_preload}" ;;
    esac
    LEAF_PM_SDL_FORCE_FULLSCREEN=1 \
    LEAF_PM_SDL_FULLSCREEN_WIDTH="\${LEAF_PM_SDL_FULLSCREEN_WIDTH:-\${DISPLAY_WIDTH:-960}}" \
    LEAF_PM_SDL_FULLSCREEN_HEIGHT="\${LEAF_PM_SDL_FULLSCREEN_HEIGHT:-\${DISPLAY_HEIGHT:-720}}" \
    LEAF_PM_ARMHF_PRELOAD="\$_leaf_pm_armhf_sdl2_preload" \
      "\$_leaf_pm_armhf_sdl2_cmd" "\$@"
  }
fi

unset _leaf_pm_controlfolder _leaf_pm_data_dir _leaf_pm_roms_dir _leaf_pm_ports_dir _leaf_pm_system_dir _leaf_pm_internal_dir _leaf_pm_python_shim_dir _leaf_pm_preload_path _leaf_pm_lib_path _leaf_pm_vk_dir _leaf_pm_sdl2_port _leaf_pm_sdl2_arches _leaf_pm_sdl2_optout _leaf_pm_aarch64_sdl2_cmd _leaf_pm_aarch64_sdl2_preload _leaf_pm_armhf_sdl2_cmd _leaf_pm_armhf_sdl2_preload
EOF

if [ -f "$hook_path" ] && command -v cmp >/dev/null 2>&1 && cmp -s "$tmp" "$hook_path"; then
  rm -f "$tmp"
else
  rm -f "$install_tmp"
  cp "$tmp" "$install_tmp"
  chmod 755 "$install_tmp"
  mv "$install_tmp" "$hook_path"
  rm -f "$tmp"
fi
trap - EXIT HUP INT TERM
